In [26]:

from pathlib import Path

cuda_code = r"""
#include <cuda_runtime.h>
#include <stdio.h>

__global__ void vector_add(const float* a, const float* b, float* c, int n) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;

    if (idx < n) {
        c[idx] = a[idx] + b[idx];
    }
}

int main() {
    const int N = 1 << 20;
    const size_t bytes = N * sizeof(float);

    float *a, *b, *c;

    cudaMallocManaged(&a, bytes);
    cudaMallocManaged(&b, bytes);
    cudaMallocManaged(&c, bytes);

    for (int i = 0; i < N; i++) {
        a[i] = 1.0f;
        b[i] = 2.0f;
    }

    int threads = 256;
    int blocks = (N + threads - 1) / threads;

    vector_add<<<blocks, threads>>>(a, b, c, N);
    cudaDeviceSynchronize();

    printf("Result: %f\n", c[0]);

    cudaFree(a);
    cudaFree(b);
    cudaFree(c);

    return 0;
}
"""

Path("vector_add.cu").write_text(cuda_code)
print("Created vector_add.cu")

Created vector_add.cu

In [37]:
!nvcc -O3 -lineinfo vector_add.cu -o vector_add

In [38]:
!ls

sample_data  vector_add  vector_add.cu

In [28]:
!nvidia-smi

Fri Oct 23 03:53:36 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [29]:
!ncu --mode launch-and-attach

==ERROR== Missing executable to launch.

In [30]:
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-1ff35a48-fdfc-9e13-a94c-2ab1fba38cc1)

In [31]:
!ncu --version

NVIDIA (R) Nsight Compute Command Line Profiler
Copyright (c) 2018-2025 NVIDIA Corporation
Version 2025.3.1.0 (build 36398880) (public-release)

In [32]:
!ncu --help

usage: ncu [options] [program] [program-arguments]

General Options:
  -h [ --help ]                         Print this help message.
  -v [ --version ]                      Print the version number.
  --mode arg (=launch-and-attach)       Select the mode of interaction with the target application:
                                          launch-and-attach
                                          (launch and attach for profiling)
                                          launch
                                          (launch and suspend for later attach)
                                          attach
                                          (attach to launched application)
  -p [ --port ] arg (=49152)            Base port for connecting to target application
  --max-connections arg (=64)           Maximum number of ports for connecting to target application
  --config-file arg (=1)                Use config.ncu-cfg config file to set parameters. Searches in the current
                                        working directory and "$HOME/.config/NVIDIA Corporation" directory.
  --config-file-path arg                Override the default path for config file.

MPS Options:
  --mps arg (=none)                     Select MPS behavior:
                                          none
                                          (No MPS support)
                                          client
                                          (Launch MPS client process)
                                          primary-client
                                          (Launch primary MPS client process)
                                          control
                                          (Launch MPS ncu control)
  --mps-num-clients arg                 Number of MPS client processes.
  --mps-timeout arg                     Timeout (seconds) to discover MPS client processes.

Launch Options:
  --check-exit-code arg (=1)            Check the application exit code and print an error if it is different than 0.
                                        If set, --replay-mode application will stop after the first pass if the exit
                                        code is not 0.
  --forward-signals                     Forwards all the signals to the application root process.
  --injection-path-32 arg (=../linux-desktop-glibc_2_11_3-x86)
                                        Override the default path for the 32-bit injection libraries.
  --injection-path-64 arg               Override the default path for the 64-bit injection libraries.
  --preload-library arg                 Prepend a shared library to be loaded by the application before the injection
                                        libraries.
  --call-stack                          Enable CPU Call Stack collection. By default, the native-type stack will be
                                        collected, cf. --call-stack-type.
  --call-stack-type arg                 Set the call stack type to be collected. More than one type may be specified.
                                        Implies --call-stack.
                                          native (default)
                                          (collect a regular CPU call stack)
                                          python
                                          (collect a Python CPU call stack)
  --nvtx                                Enable NVTX support.
  --support-32bit                       Support profiling processes launched from 32-bit applications.
  --target-processes arg (=all)         Select the processes you want to profile:
                                          application-only
                                          (profile only the application process)
                                          all
                                          (profile the application and its child processes)
  --target-processes-filter arg         Set the comma separated expressions to filter which processes are profiled.
                                          <process name> Set the exact process name to include for profiling.
                                          regex:<expression> Set the regex to include matching process names for
                                        profiling.
                                            On shells that recognize regular expression symbols as special characters,
                                            the expression needs to be escaped with quotes.
                                          exclude:<process name> Set the exact process name to exclude for profiling.
                                          exclude-tree:<process name> Set the exact process name to exclude
                                            for profiling and further process tracking. None of its child processes
                                            will be profiled, even if they match a positive filter.
                                        The executable name part of the process will be considered in the match.
                                        Processing of filters stops at the first match.
                                        If any positive filter is specified, only processes matching a positive filter
                                        are profiled.
  --null-stdin                          Launch the application with '/dev/null' as its standard input. This avoids
                                        applications reading from standard input being stopped by SIGTTIN signals and
                                        hanging when running as backgrounded processes.
  --nvtx-push-pop-scope arg (=thread)   Specify scope of push-pop ranges:
                                           thread (default) : NVTX Push/Pop ranges are scoped per thread.
                                           process          : NVTX push/pop ranges are scoped per process.

Attach Options:
  --hostname arg                        Set hostname / ip address for connection target.

Common Profile Options:
  --kill arg (=0)                       Terminate the target application when the requested --launch-count was
                                        profiled.
  --replay-mode arg (=kernel)           Mechanism used for replaying a kernel launch multiple times to collect all
                                        requested profiling data:
                                          kernel (default)
                                          (Replay individual kernel launches transparently
                                           during the execution of the application.)
                                          application
                                          (Relaunch the entire application multiple times.
                                           Requires deterministic program execution.)
                                          range
                                          (Replay ranges of kernel launches and API calls
                                           during the execution of the application.)
                                          app-range
                                          (Profile ranges without API capture by relaunching
                                           the entire application multiple times.
                                           Requires deterministic program execution.)
  --app-replay-buffer arg (=file)       Application replay buffer location:
                                          file (default)
                                          (Replay pass data is buffered in a temporary file. The report is created
                                        after profiling completed.)
                                          memory
                                          (Replay pass data is buffered in memory, and the report is created while
                                        profiling.)
  --app-replay-match arg (=grid)        Application replay kernel matching strategy, per process and device:
                                          name
                                          (Matched by name)
                                          grid (default)
                                          (Matched by name and grid/block size)
                                          all
                                          (Matched by name, grid/block size, context id and stream id)
  --app-replay-mode arg (=balanced)     Application replay kernel matching mode:
                                          strict   : Requires all filtered kernels to match across all
                                                     replay passes in the exact order.
                                          balanced : Requires all filtered kernels to match across all
                                          (default)  replay passes, without strict ordering.
                                          relaxed  : Produces results only for filtered kernels that could
                                                     be matched across replay passes. Unmatched kernels are
                                                     dropped.
  --graph-profiling arg (=node)         CUDA graph profiling mode:
                                          node (default)
                                          (Profile individual kernel nodes)
                                          graph
                                          (Profile entire graphs)
  --range-replay-options arg            Range replay options, separated by comma:
                                          enable-greedy-sync
                                          (Insert ctx sync for applicable deferred APIs during capture)
                                          disable-host-restore
                                          (Disable restoring device-written host allocations)
                                          disable-host-save
                                          (Disable saving device-mapped host allocations for every kernel but capture
                                        it only once before the first kernel launch)
                                          disable-dependent-kernel-detection
                                          (Disable dependent kernel detection before capturing device-mapped host
                                        allocations for each kernel)
  --list-sets                           List all section sets found in the search paths.
  --set arg                             Identifier of section set to collect. If not specified, the basic set is
                                        collected.
  --list-sections                       List all sections found in the search paths.
  --section-folder arg                  Search path for section files. Not recursive.
  --section-folder-recursive arg        Search path for section files. Recursive.
  --section-folder-restore              Restore stock files to the default section folder or the folder specified by
                                        --section-folder.
  --list-rules                          List all analysis rules found in the search paths.
  --apply-rules arg (=1)                Apply analysis rules for collected sections. If --rule is not set, all
                                        available rules are applied. Allowed values:
                                          on/off
                                          yes/no
  --rule arg                            Identifier of rule to apply. Enables --apply-rules yes.
  --import-sass arg (=1)                Import ELF cubins into the report. Cubins include SASS, PTX and meta
                                        information. Allowed values:
                                          on/off
                                          yes/no
  --import-source arg (=0)              If available from -lineinfo, correlated CUDA source files are permanently
                                        imported into the report. Allowed values:
                                          on/off
                                          yes/no
  --source-folders arg                  Comma separated search paths for correlated CUDA source files to import into
                                        the report if --import-source option is enabled. Recursive.
  --list-metrics                        List all metrics to be collected based on selected sections.
  --query-metrics                       Query available metrics for devices on the system. Use --devices and --chips to
                                        filter which devices to query. By default, metrics reported by this option
                                        require a suffix to be collected. See --query-metrics-mode for details.
  --query-metrics-mode arg (=base)      Set the mode for querying metrics. Implies --query-metrics.
                                        Available modes:
                                          base (default)
                                          (base names for metrics)
                                          suffix
                                          (suffix names for metrics. Use --metrics to specify the base metrics to
                                        query)
                                          all
                                          (full names for metrics)
  --query-metrics-collection arg (=profiling)
                                        Set which metric collection kind to query. Implies --query-metrics.
                                        Available modes:
                                          device
                                          (query CUDA device attributes)
                                          groups
                                          (query metric groups)
                                          launch
                                          (query launch attributes)
                                          numa
                                          (query NUMA topology metrics)
                                          nvlink
                                          (query metrics related to NVLink)
                                          pmsampling
                                          (query metrics available for pm sampling)
                                          profiling (default)
                                          (query metrics available for profiling)
                                          source
                                          (query source metrics)
                                          stats
                                          (query metrics generated by the profiler to inform about profiling
                                        statistics)
                                          warpsampling
                                          (query metrics available for periodic sampling of the warp program counter
                                        and warp scheduler state)
  --list-chips                          List all supported chips that can be used with --chips.
  --chips arg                           Specify the chips for querying metrics, separated by comma.
  --profile-from-start arg (=1)         Set if application should be profiled from its start. Allowed values:
                                          on/off
                                          yes/no
  --disable-profiler-start-stop         Disable start/stop profiling. When set, cu(da)ProfilerStart/Stop APIs are
                                        ignored.
  --quiet                               Suppress all profiler output.
  --verbose                             Make profiler output more verbose.
  --cache-control arg (=all)            Control the behavior of the GPU caches during profiling. Allowed values:
                                          all
                                          none
  --clock-control arg (=base)           Control the behavior of the GPU clocks during profiling. Allowed values:
                                          base
                                          (Lock GPU clocks to base)
                                          none
                                          (Don't lock clocks)
                                          reset
                                          (Reset GPU clocks and exit)
  --pipeline-boost-state arg (=stable)  Control the Tensor Core boost state. Setting stable Tensor Core boosting is
                                        recommended for application performance profiling ensuring predictive run to
                                        run performance.
                                          stable
                                          (Set the Tensor Core boost state to stable)
                                          dynamic
                                          (Set the Tensor Core boost state to dynamic)

Filter Profile Options:
  --devices arg                         Specify the devices to enable profiling on, separated by comma. By default all
                                        devices are enabled.
  --filter-mode arg (=global)           Set the filter mode for kernel launches. Available modes:
                                           global (default) : Apply provided launch filters on kernel launches
                                                              collectively.
                                           per-gpu          : Apply provided launch filters on kernel launches
                                                              separately on each device. Effective launch filters
                                                              for this mode are --launch-count and --launch-skip.
                                           per-launch-config: Apply kernel filters and launch filters on kernel
                                                              launches separately for each GPU launch parameter
                                                              i.e. Grid Size, Block Size and Shared Memory

  --kernel-id arg                       Set the identifier to use for matching the kernel to profile. The identifier is
                                        of the format "context-id:stream-id:[name-operator:]kernel-name:invocation-nr".
                                        Skip entries that shouldn't be matched, e.g. use "::foobar:2" to match the
                                        second invocation of "foobar" in any context or stream. Use ":7:regex:^foo:" to
                                        match any kernel in stream 7 beginning with "foo" (according to
                                        --kernel-name-base).
  -k [ --kernel-name ] arg              Filter the kernel in one of the following ways:
                                          <kernel name> Set the kernel name for an exact match.
                                          regex:<expression> Set the regex to use for matching the kernel name.
  --kernel-name-base arg (=function)    Set the basis for --kernel-name, --kernel-id and kernel-name:
                                          function
                                          demangled
                                          mangled
  --rename-kernels arg (=1)             Perform simplification on the kernel demangled names.
                                        Rename demangled names using a config file. By default, searches for
                                        ncu-kernel-renames.yaml config file in the current working directory and
                                        "$HOME/.config/NVIDIA Corporation" directory. Use --rename-kernels-export
                                        option to export the simplified demangled names to the config file.
  --rename-kernels-export arg (=0)      Export renamed or simplified kernel demangled names to the config file.

In [33]:
!ncu --list-sets

---------- --------------------------------------------------------------------------- ------- -----------------
Identifier Sections                                                                    Enabled Estimated Metrics
---------- --------------------------------------------------------------------------- ------- -----------------
basic      LaunchStats, Occupancy, SpeedOfLight, WorkloadDistribution                  yes     213
detailed   ComputeWorkloadAnalysis, LaunchStats, MemoryWorkloadAnalysis, MemoryWorkloa no      906
           dAnalysis_Chart, Occupancy, SourceCounters, SpeedOfLight, SpeedOfLight_Roof
           lineChart, WorkloadDistribution
full       ComputeWorkloadAnalysis, InstructionStats, LaunchStats, MemoryWorkloadAnaly no      7794
           sis, MemoryWorkloadAnalysis_Chart, MemoryWorkloadAnalysis_Tables, NumaAffin
           ity, Nvlink_Tables, Nvlink_Topology, Occupancy, PmSampling, SchedulerStats,
            SourceCounters, SpeedOfLight, SpeedOfLight_HierarchicalDoubleRooflineChart
           , SpeedOfLight_HierarchicalHalfRooflineChart, SpeedOfLight_HierarchicalSing
           leRooflineChart, SpeedOfLight_HierarchicalTensorRooflineChart, SpeedOfLight
           _RooflineChart, WarpStateStats, WorkloadDistribution
nvlink     Nvlink, Nvlink_Tables, Nvlink_Topology                                      no      122
pmsampling PmSampling, PmSampling_WarpStates                                           no      411
roofline   SpeedOfLight, SpeedOfLight_HierarchicalDoubleRooflineChart, SpeedOfLight_Hi no      6649
           erarchicalHalfRooflineChart, SpeedOfLight_HierarchicalSingleRooflineChart,
           SpeedOfLight_HierarchicalTensorRooflineChart, SpeedOfLight_RooflineChart, W
           orkloadDistribution

NCU Sets (Nsight Compute Sets) are predefined collections of GPU performance metrics that NVIDIA Nsight Compute measures together.

ELI5 analogy: Imagine taking your car to a mechanic. Instead of checking every single part, you ask for a specific type of inspection—engine performance, fuel efficiency, or a complete inspection. NCU sets work similarly for GPU kernels.

Common NCU Sets

| Set      | What it measures                                                                             |
|----------|---------------------------------------------------------------------------------------------|
| basic    | Essential performance metrics, such as kernel execution time and basic hardware utilization. |
| detailed | More comprehensive information about memory, compute, and GPU execution behavior.            |
| full     | A broad collection of available profiling metrics and analysis sections.                      |

In [34]:
!ncu --list-sets

---------- --------------------------------------------------------------------------- ------- -----------------
Identifier Sections                                                                    Enabled Estimated Metrics
---------- --------------------------------------------------------------------------- ------- -----------------
basic      LaunchStats, Occupancy, SpeedOfLight, WorkloadDistribution                  yes     213
detailed   ComputeWorkloadAnalysis, LaunchStats, MemoryWorkloadAnalysis, MemoryWorkloa no      906
           dAnalysis_Chart, Occupancy, SourceCounters, SpeedOfLight, SpeedOfLight_Roof
           lineChart, WorkloadDistribution
full       ComputeWorkloadAnalysis, InstructionStats, LaunchStats, MemoryWorkloadAnaly no      7794
           sis, MemoryWorkloadAnalysis_Chart, MemoryWorkloadAnalysis_Tables, NumaAffin
           ity, Nvlink_Tables, Nvlink_Topology, Occupancy, PmSampling, SchedulerStats,
            SourceCounters, SpeedOfLight, SpeedOfLight_HierarchicalDoubleRooflineChart
           , SpeedOfLight_HierarchicalHalfRooflineChart, SpeedOfLight_HierarchicalSing
           leRooflineChart, SpeedOfLight_HierarchicalTensorRooflineChart, SpeedOfLight
           _RooflineChart, WarpStateStats, WorkloadDistribution
nvlink     Nvlink, Nvlink_Tables, Nvlink_Topology                                      no      122
pmsampling PmSampling, PmSampling_WarpStates                                           no      411
roofline   SpeedOfLight, SpeedOfLight_HierarchicalDoubleRooflineChart, SpeedOfLight_Hi no      6649
           erarchicalHalfRooflineChart, SpeedOfLight_HierarchicalSingleRooflineChart,
           SpeedOfLight_HierarchicalTensorRooflineChart, SpeedOfLight_RooflineChart, W
           orkloadDistribution

In [35]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Wed_Aug_20_01:58:59_PM_PDT_2025
Cuda compilation tools, release 13.0, V13.0.88
Build cuda_13.0.r13.0/compiler.36424714_0

In [36]:
!nvcc --help

Usage  : nvcc [options] <inputfile>

Options for specifying the compilation phase
============================================
More exactly, this option specifies up to which stage the input files must be compiled,
according to the following compilation trajectories for different input file types:
        .c/.cc/.cpp/.cxx : preprocess, compile, link
        .o               : link
        .i/.ii           : compile, link
        .cu              : preprocess, cuda frontend, PTX assemble,
                           merge with host C code, compile, link
        .gpu             : cicc compile into cubin
        .ptx             : PTX assemble into cubin.

--cuda                                              (-cuda)
        Compile all .cu input files to .cu.cpp.ii output.

--cubin                                             (-cubin)
        Compile all .cu/.gpu/.ptx input files to device-only .cubin files.  This
        step discards the host code for each .cu input file.

--fatbin                                            (-fatbin)
        Compile all .cu/.gpu/.ptx/.cubin input files to device-only .fatbin files.
        This step discards the host code for each .cu input file.

--ptx                                               (-ptx)
        Compile all .cu input files to device-only .ptx files.  This step discards
        the host code for each of these input file.

--optix-ir                                          (-optix-ir)
        Compile CUDA source to OptiX IR (.optixir) output. The OptiX IR is only intended
        for consumption by OptiX through appropriate APIs. This feature is not supported
        with link-time-optimization (-dlto), the lto_NN -arch target, or with -gencode.

--ltoir                                             (-ltoir)
        Compile CUDA source to device-only .ltoir file.  This feature is only supported
        with link-time-optimization (-dlto).  This step discards the host code for
        each .cu input file.

--preprocess                                        (-E)
        Preprocess all .c/.cc/.cpp/.cxx/.cu input files.

--generate-dependencies                             (-M)
        Generate a dependency file that can be included in a make file for the .c/.cc/.cpp/.cxx/.cu
        input file. If -MF is specified, multiple source files are not supported,
        and the output is written to the specified file, otherwise it is written
        to stdout.

--generate-nonsystem-dependencies                   (-MM)
        Same as --generate-dependencies but skip header files found in system directories
        (Linux only).

--generate-dependencies-with-compile                (-MD)
        Generate a dependency file and compile the input file. The dependency file
        can be included in a make file for the .c/.cc/.cpp/.cxx/.cu input file.
        This option cannot be specified together with -E.
        The dependency file name is computed as follows:
        - If -MF is specified, then the specified file is used as the dependency
        file name
        - If -o is specified, the dependency file name is computed from the specified
        file name by replacing the suffix with '.d'.
        - Otherwise, the dependency file name is computed by replacing the input
        file names's suffix with '.d'
        If the dependency file name is computed based on either -MF or -o, then multiple
        input files are not supported.

--generate-nonsystem-dependencies-with-compile      (-MMD)
        Same as --generate-dependencies-with-compile, but skip header files found
        in system directories (Linux only).

--dependency-output                                 (-MF)
        Specify the output file for the dependency file generated with -M/-MM/-MD/-MMD.


--generate-dependency-targets                       (-MP)
        Add an empty target for each dependency.

--compile                                           (-c)
        Compile each .c/.cc/.cpp/.cxx/.cu input file into an object file.

--device-c                                          (-dc)
        Compile each .c/.cc/.cpp/.cxx/.cu input file into an object file that contains
        relocatable device code.  It is equivalent to '--relocatable-device-code=true
        --compile'.

--device-w                                          (-dw)
        Compile each .c/.cc/.cpp/.cxx/.cu input file into an object file that contains
        executable device code.  It is equivalent to '--relocatable-device-code=false
        --compile'.

--device-link                                       (-dlink)
        Link object files with relocatable device code and .ptx/.cubin/.fatbin files
        into an object file with executable device code, which can be passed to the
        host linker.

--link                                              (-link)
        This option specifies the default behavior: compile and link all inputs.

--lib                                               (-lib)
        Compile all inputs into object files (if necessary) and add the results to
        the specified output library file.

--run                                               (-run)
        This option compiles and links all inputs into an executable, and executes
        it.  Or, when the input is a single executable, it is executed without any
        compilation or linking. This step is intended for developers who do not want
        to be bothered with setting the necessary environment variables; these are
        set temporarily by nvcc).


File and path specifications.
=============================

--output-file <file>                                (-o)
        Specify name and location of the output file.  Only a single input file is
        allowed when this option is present in nvcc non-linking/archiving mode.

--pre-include <file>,...                            (-include)
        Specify header files that must be preincluded during preprocessing.

--objdir-as-tempdir                                 (-objtemp)
        Create intermediate files in the same directory as the object file instead
        of in the temporary directory. This option will take effect only if -c, -dc
        or -dw is also used.

--library <library>,...                             (-l)
        Specify libraries to be used in the linking stage without the library file
        extension.  The libraries are searched for on the library search paths that
        have been specified using option '--library-path'.

--define-macro <def>,...                            (-D)
        Specify macro definitions to define for use during preprocessing or compilation.

--undefine-macro <def>,...                          (-U)
        Undefine macro definitions during preprocessing or compilation.

--include-path <path>,...                           (-I)
        Specify include search paths.

--system-include <path>,...                         (-isystem)
        Specify system include search paths.

--library-path <path>,...                           (-L)
        Specify library search paths.

--output-directory <directory>                      (-odir)
        Specify the directory of the output file.  This option is intended for letting
        the dependency generation step (see '--generate-dependencies') generate a
        rule that defines the target object file in the proper directory.

--compiler-bindir <path>                            (-ccbin)
        Specify the directory in which the host compiler executable resides.  The
        host compiler executable name can be also specified to ensure that the correct
        host compiler is selected.  In addition, driver prefix options ('--input-drive-prefix',
        '--dependency-drive-prefix', or '--drive-prefix') may need to be specified,
        if nvcc is executed in a Cygwin shell or a MinGW shell on Windows.

--allow-unsupported-compiler                        (-allow-unsupported-compiler)
        Disable nvcc check for supported host compiler versions. Using an unsupported
        host compiler may cause compilation failure or incorrect run time execution.
        Use at your own risk. This option has no effect on MacOS.

--archiver-binary <path>                            (-arbin)
        Specify the path of the executable for the archiving tool used to createstatic
        libraries with '--lib'. If unspecified, a platform-specific defaultis used.

--cudart {none|shared|static}                       (-cudart)
        Specify the type of CUDA runtime library to be used: no CUDA runtime library,
        shared/dynamic CUDA runtime library, or static CUDA runtime library.
        Allowed values for this option:  'none','shared','static'.
        Default value:  'static'.

--cudadevrt {none|static}                           (-cudadevrt)
        Specify the type of CUDA device runtime library to be used: no CUDA device
        runtime library, or static CUDA device runtime library.
        Allowed values for this option:  'none','static'.
        Default value:  'static'.

--libdevice-directory <directory>                   (-ldir)
        Specify the directory that contains the libdevice library files when option
        '--dont-use-profile' is used.  Libdevice library files are located in the
        'nvvm/libdevice' directory in the CUDA toolkit.

--target-directory <string>                         (-target-dir)
        Specify the subfolder name in the targets directory where the default include
        and library paths are located.

--use-local-env                                     (-use-local-env)
        Use this flag to force nvcc to assume that the environment for cl.exe has
        already been set up, and skip running the batch file from the MSVC installation
        that sets up the environment for cl.exe. This can significantly reduce overall
        compile time for small programs.

--force-cl-env-setup                                (-force-cl-env-setup)
        Force nvcc to always run the batch file from the MSVC installation to set
        up the environment for cl.exe(matching legacy nvcc behavior).

        If this flag is not specified, by default, nvcc will skip running the batch
        file if the following conditions are satisfied : cl.exe is in the PATH, environment
        variable VSCMD_VER is set, and, if -ccbin is specified, then compiler denoted
        by -ccbin matches the cl.exe in the PATH.

        Skipping the batch file execution can reduce overall compile time significantly
        for small programs.


Options for specifying behavior of compiler/linker.
===================================================

--profile                                           (-pg)
        Instrument generated code/executable for use by gprof (Linux only).

--debug                                             (-g)
        Generate debug information for host code.

--device-debug                                      (-G)
        Generate debug information for device code. If --dopt is not specified, then
        turns off all optimizations. Don't use for profiling; use -lineinfo instead.

--generate-line-info                                (-lineinfo)
        Generate line-number information for device code.

--optimization-info <kind>,...                      (-opt-info)
        Provide optimization reports for the specified kind of optimization. The
        following tags are supported:
                inline: Emit remarks related to function inlining. Inlining passmay
        be invoked multiple times by the compiler and a function notinlined in an
        earlier pass may be inlined in a subsequent pass.
        Allowed values for this option:  'inline'.

--optimize <level>                                  (-O)
        Specify optimization level for host code.

--Ofast-compile <level>                             (-Ofc)
        Specify fast-compile level for device code, which controls the tradeoff between
        compilation speed and runtime performance by disabling certain optimizations
        at varying levels.
        Levels:
                'max': Focus only on the fastest compilation speed, disabling many
        optimizations.
                'mid': Balance compile time and runtime, disabling expensive optimizations.
                'min': More minimal impact on both compile time and runtime, minimizing
        some expensive optimizations.
                '0': Disables fast-compile.
        The option is disabled by default.
        Allowed values for this option:  '0','max','mid','min'.

--dopt <kind>                                       (-dopt)
        Enable device code optimization. When specified along with '-G', enables
        limited debug information generation for optimized device code (currently,
        only line number information). When '-G' is not specified, '-dopt=on' is
        implicit.
        Allowed values for this option:  'on'.

--dlink-time-opt                                    (-dlto)
        Perform link-time optimization of device code. Link-time optimization must
        be specified at both compile and link time; at compile time it stores high-level
        intermediate code, then at link time it links together and optimizes the
        intermediate code.If that intermediate is not found at link time then nothing
        happens. Intermediate code is also stored at compile time with the --gpu-code='lto_NN'
        target. The options -dlto -arch=sm_NN will add a lto_NN target; if you want
        to only add a lto_NN target and not the compute_NN that -arch=sm_NN usually
        generates, use -arch=lto_NN. The options '-dlto -dlink -ptx -o <file.ptx>'
        will cause nvlink to generate <file.ptx>. If -o is not used, the file generated
        will be a_dlink.dlto.ptx.

--lto                                               (-lto)
        Alias for -dlto.

--gen-opt-lto                                       (-gen-opt-lto)
        Run the optimizer passes before generating the LTO IR.

--ftemplate-backtrace-limit <limit>                 (-ftemplate-backtrace-limit)
        Set the maximum number of template instantiation notes for a single warning
        or error to <limit>. A value of 0 is allowed, and indicates that no limit
        should be enforced. This value is also passed to the host compiler if it
        provides an equivalent flag.

--ftemplate-depth <limit>                           (-ftemplate-depth)
        Set the maximum instantiation depth for template classes to <limit>. This
        value is also passed to the host compiler if it provides an equivalent flag.

--no-exceptions                                     (-noeh)
        Disable exception handling for host code.

--shared                                            (-shared)
        Generate a shared library during linking.  Use option '--linker-options'
        when other linker options are required for more control.

--x {c|c++|cu}                                      (-x)
        Explicitly specify the language for the input files, rather than letting
        the compiler choose a default based on the file name suffix.
        Allowed values for this option:  'c','c++','cu'.

--std {c++03|c++11|c++14|c++17|c++20}               (-std)
        Select a particular C++ dialect.  Note that this flag also turns on the corresponding
        dialect flag for the host compiler.
        Allowed values for this option:  'c++03','c++11','c++14','c++17','c++20'.

--no-host-device-initializer-list                   (-nohdinitlist)
        Do not implicitly consider member functions of std::initializer_list as __host__
        __device__ functions.

--no-host-device-move-forward                       (-nohdmoveforward)
        Do not implicitly consider std::move and std::forward as __host__ __device__
        function templates.

--expt-relaxed-constexpr                            (-expt-relaxed-constexpr)
        Experimental flag: Allow host code to invoke __device__ constexpr functions,
        and device code to invoke __host__ constexpr functions.Note that the behavior
        of this flag may change in future compiler releases.

--extended-lambda                                   (-extended-lambda)
        Allow __host__, __device__ annotations in lambda declaration.

--expt-extended-lambda                              (-expt-extended-lambda)
        Alias for -extended-lambda.

--machine {64}                                      (-m)
        Specify 64 bit architecture.
        Allowed values for this option:  64.
        Default value:  64.

--m64                                               (-m64)
        Equivalent to --machine=64.


Options for passing specific phase options
==========================================
These allow for passing options directly to the intended compilation phase.  Using
these, users have the ability to pass options to the lower level compilation tools,
without the need for nvcc to know about each and every such option.

--compiler-options <options>,...                    (-Xcompiler)
        Specify options directly to the compiler/preprocessor.

--linker-options <options>,...                      (-Xlinker)
        Specify options directly to the host linker.

--archive-options <options>,...                     (-Xarchive)
        Specify options directly to library manager.

--ptxas-options <options>,...                       (-Xptxas)
        Specify options directly to ptxas, the PTX optimizing assembler.

--nvlink-options <options>,...                      (-Xnvlink)
        Specify options directly to nvlink.


Miscellaneous options for guiding the compiler driver.
======================================================

--static-global-template-stub {true|false}          (-static-global-template-stub)
        In whole-program compilation mode (-rdc=false), force 'static' linkage for
        host side stub functions generated for __global__ function templates.

        When this flag is false, a __global__ template stub function in the C++ code
        sent to the host compiler will have weak linkage. This can cause a correctness
        problem if template instantiations of the __global__ template are present
        in multiple translation units, since the host linker will chose only one
        of the stub instantiations in the linked host program, but the device code
        in each translation unit forms a separate device program with a distinct
        version of the __global__ template instantiation. Thus, launching a __global__
        template instantiation from one translation unit may unexpectedly launch
        the kernel in a a device program from a different translation unit that contains
        the same __global__ function template instantiation. Please see nvcc documentation
        for details.

        Setting this flag to true avoids the problem, since the CUDA compiler will
        force 'static' linkage for the __global__ template stub function, and so
        the __global__ template stub will be unique across multiple translation units.

        Note:
        -This option is ignored unless the program is being compiled in whole program
        compilation mode (-rdc=false).
        -Turning on this flag may break existing code in some corner cases (only
        in whole program compilation mode):
                a. If a __global__ function template is declared as a friend, and
        the friend declaration is the first declaration of the entity.
                b. If a __global__  function template is referenced, but not defined
        in the current translation unit.
        Default value:  true.

--device-entity-has-hidden-visibility {true|false}  (-device-entity-has-hidden-visibility)
        This flag applies to __global__ functions and function templates, and to
        __constant__ , __device__ and __managed__ variables and variable templates,

In [39]:
!ncu --set basic ./vector_add

==PROF== Connected to process 10549 (/content/vector_add)
==PROF== Profiling "vector_add" - 0: 0%....50%....100% - 10 passes
Result: 3.000000
==PROF== Disconnected from process 10549
[10549] vector_add@127.0.0.1
  vector_add(const float *, const float *, float *, int) (4096, 1, 1)x(256, 1, 1), Context 1, Stream 7, Device 0, CC 7.5
    Section: GPU Speed Of Light Throughput
    ----------------------- ----------- ------------
    Metric Name             Metric Unit Metric Value
    ----------------------- ----------- ------------
    DRAM Frequency                  Ghz         4.56
    SM Frequency                    Mhz       584.10
    Elapsed Cycles                cycle       29,482
    Memory Throughput                 %        90.45
    DRAM Throughput                   %        90.45
    Duration                         us        50.46
    L1/TEX Cache Throughput           %        31.73
    L2 Cache Throughput               %        28.64
    SM Active Cycles              cycle    25,401.45
    Compute (SM) Throughput           %        24.25
    ----------------------- ----------- ------------

    INF   This workload is utilizing greater than 80.0% of the available compute or memory performance of the device.
          To further improve performance, work will likely need to be shifted from the most utilized to another unit.
          Start by analyzing DRAM in the Memory Workload Analysis section.

    Section: Launch Statistics
    -------------------------------- --------------- ---------------
    Metric Name                          Metric Unit    Metric Value
    -------------------------------- --------------- ---------------
    Block Size                                                   256
    Function Cache Configuration                     CachePreferNone
    Grid Size                                                  4,096
    Registers Per Thread             register/thread              16
    Shared Memory Configuration Size           Kbyte           32.77
    Driver Shared Memory Per Block        byte/block               0
    Dynamic Shared Memory Per Block       byte/block               0
    Static Shared Memory Per Block        byte/block               0
    # SMs                                         SM              40
    Stack Size                                                 1,024
    Threads                                   thread       1,048,576
    # TPCs                                                        20
    Enabled TPC IDs                                              all
    Uses Green Context                                             0
    Waves Per SM                                               25.60
    -------------------------------- --------------- ---------------

    Section: Occupancy
    ------------------------------- ----------- ------------
    Metric Name                     Metric Unit Metric Value
    ------------------------------- ----------- ------------
    Block Limit SM                        block           16
    Block Limit Registers                 block           16
    Block Limit Shared Mem                block           16
    Block Limit Warps                     block            4
    Theoretical Active Warps per SM        warp           32
    Theoretical Occupancy                     %          100
    Achieved Occupancy                        %        89.34
    Achieved Active Warps Per SM           warp        28.59
    ------------------------------- ----------- ------------

    OPT   Est. Local Speedup: 10.66%
          The difference between calculated theoretical (100.0%) and measured achieved occupancy (89.3%) can be the
          result of warp scheduling overheads or workload imbalances during the kernel execution. Load imbalances can
          occur between warps within a block as well as across blocks of the same kernel. See the CUDA Best Practices
          Guide (https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#occupancy) for more details on
          optimizing occupancy.

    Section: GPU and Memory Workload Distribution
    -------------------------- ----------- ------------
    Metric Name                Metric Unit Metric Value
    -------------------------- ----------- ------------
    Average DRAM Active Cycles       cycle      207,929
    Total DRAM Elapsed Cycles        cycle    1,839,104
    Average L1 Active Cycles         cycle    25,401.45
    Total L1 Elapsed Cycles          cycle    1,081,144
    Average L2 Active Cycles         cycle    36,785.78
    Total L2 Elapsed Cycles          cycle    1,378,688
    Average SM Active Cycles         cycle    25,401.45
    Total SM Elapsed Cycles          cycle    1,081,144
    Average SMSP Active Cycles       cycle    25,263.56
    Total SMSP Elapsed Cycles        cycle    4,324,576
    -------------------------- ----------- ------------

In [40]:
!ncu --set full -o vector_add_report -f ./vector_add

==PROF== Connected to process 10712 (/content/vector_add)
==PROF== Profiling "vector_add" - 0: 0%....50%....100% - 33 passes
Result: 3.000000
==PROF== Disconnected from process 10712
==PROF== Report: /content/vector_add_report.ncu-rep

In [41]:
!ls

sample_data  vector_add  vector_add.cu	vector_add_report.ncu-rep

Download from remote locally using b64 and Ipython.display

In [44]:

import base64
from pathlib import Path
from IPython.display import display, HTML

file_path = Path("vector_add_report.ncu-rep")
data = base64.b64encode(file_path.read_bytes()).decode()

display(HTML(
    f'<a download="{file_path.name}" '
    f'href="data:application/octet-stream;base64,{data}">'
    f'Download {file_path.name}</a>'
))

Use this to load files to the drive (google drive mount)

In [ ]:
from google.colab import drive
from pathlib import Path
import shutil

drive.mount("/content/drive")

source = Path("vector_add_report.ncu-rep")
destination = Path("/content/drive/MyDrive/GPU-Reports")
destination.mkdir(parents=True, exist_ok=True)

shutil.copy2(source, destination / source.name)

In [45]:
!ncu --set full ./vector_add

==PROF== Connected to process 12108 (/content/vector_add)
==PROF== Profiling "vector_add" - 0: 0%....50%....100% - 33 passes
Result: 3.000000
==PROF== Disconnected from process 12108
[12108] vector_add@127.0.0.1
  vector_add(const float *, const float *, float *, int) (4096, 1, 1)x(256, 1, 1), Context 1, Stream 7, Device 0, CC 7.5
    Section: GPU Speed Of Light Throughput
    ----------------------- ----------- ------------
    Metric Name             Metric Unit Metric Value
    ----------------------- ----------- ------------
    DRAM Frequency                  Ghz         4.56
    SM Frequency                    Mhz       584.41
    Elapsed Cycles                cycle       29,536
    Memory Throughput                 %        90.33
    DRAM Throughput                   %        90.33
    Duration                         us        50.53
    L1/TEX Cache Throughput           %        31.77
    L2 Cache Throughput               %        28.59
    SM Active Cycles              cycle    25,422.78
    Compute (SM) Throughput           %        24.26
    ----------------------- ----------- ------------

    INF   This workload is utilizing greater than 80.0% of the available compute or memory performance of the device.
          To further improve performance, work will likely need to be shifted from the most utilized to another unit.
          Start by analyzing DRAM in the Memory Workload Analysis section.

    Section: GPU Speed Of Light Roofline Chart
    INF   The ratio of peak float (FP32) to double (FP64) performance on this device is 32:1. The workload achieved
          close to 1% of this device's FP32 peak performance and 0% of its FP64 peak performance. See the Profiling
          Guide (https://docs.nvidia.com/nsight-compute/ProfilingGuide/index.html#roofline) for more details on
          roofline analysis.

    Section: PM Sampling
    ------------------------- ----------- ------------
    Metric Name               Metric Unit Metric Value
    ------------------------- ----------- ------------
    Maximum Buffer Size             Kbyte       262.14
    Maximum Sampling Interval       cycle       20,000
    # Pass Groups                                    1
    ------------------------- ----------- ------------

    WRN   Sampling interval is larger than 10% of the workload duration, which likely results in very few collected
          samples.

    Section: Compute Workload Analysis
    -------------------- ----------- ------------
    Metric Name          Metric Unit Metric Value
    -------------------- ----------- ------------
    Executed Ipc Active   inst/cycle         0.48
    Executed Ipc Elapsed  inst/cycle         0.45
    Issue Slots Busy               %        11.46
    Issued Ipc Active     inst/cycle         0.49
    SM Busy                        %        11.46
    -------------------- ----------- ------------

    OPT   Est. Local Speedup: 92.42%
          All compute pipelines are under-utilized. Either this workload is very small or it doesn't issue enough warps
          per scheduler. Check the Launch Statistics and Scheduler Statistics sections for further details.

    Section: Memory Workload Analysis
    -------------------------------------- ----------- ------------
    Metric Name                            Metric Unit Metric Value
    -------------------------------------- ----------- ------------
    Local Memory Spilling Requests                                0
    Local Memory Spilling Request Overhead           %            0
    Memory Throughput                          Gbyte/s       263.62
    Mem Busy                                         %        28.59
    Max Bandwidth                                    %        90.33
    L1/TEX Hit Rate                                  %            0
    L2 Hit Rate                                      %        33.56
    Mem Pipes Busy                                   %        24.26
    -------------------------------------- ----------- ------------

    Section: Scheduler Statistics
    ---------------------------- ----------- ------------
    Metric Name                  Metric Unit Metric Value
    ---------------------------- ----------- ------------
    One or More Eligible                   %        12.22
    Issued Warp Per Scheduler                        0.12
    No Eligible                            %        87.78
    Active Warps Per Scheduler          warp         6.24
    Eligible Warps Per Scheduler        warp         0.14
    ---------------------------- ----------- ------------

    OPT   Est. Local Speedup: 9.668%
          Every scheduler is capable of issuing one instruction per cycle, but for this workload each scheduler only
          issues an instruction every 8.2 cycles. This might leave hardware resources underutilized and may lead to
          less optimal performance. Out of the maximum of 8 warps per scheduler, this workload allocates an average of
          6.24 active warps per scheduler, but only an average of 0.14 warps were eligible per cycle. Eligible warps
          are the subset of active warps that are ready to issue their next instruction. Every cycle with no eligible
          warp results in no instruction being issued and the issue slot remains unused. To increase the number of
          eligible warps, reduce the time the active warps are stalled by inspecting the top stall reasons on the Warp
          State Statistics and Source Counters sections.

    Section: Warp State Statistics
    ---------------------------------------- ----------- ------------
    Metric Name                              Metric Unit Metric Value
    ---------------------------------------- ----------- ------------
    Warp Cycles Per Issued Instruction             cycle        51.11
    Warp Cycles Per Executed Instruction           cycle        51.51
    Avg. Active Threads Per Warp                                   32
    Avg. Not Predicated Off Threads Per Warp                    29.87
    ---------------------------------------- ----------- ------------

    OPT   Est. Speedup: 9.668%
          On average, each warp of this workload spends 40.1 cycles being stalled waiting for a scoreboard dependency
          on a L1TEX (local, global, surface, texture) operation. Find the instruction producing the data being waited
          upon to identify the culprit. To reduce the number of cycles waiting on L1TEX data accesses verify the
          memory access patterns are optimal for the target architecture, attempt to increase cache hit rates by
          increasing data locality (coalescing), or by changing the cache configuration. Consider moving frequently
          used data to shared memory. This stall type represents about 78.5% of the total average of 51.1 cycles
          between issuing two instructions.
    ----- --------------------------------------------------------------------------------------------------------------
    INF   Check the Warp Stall Sampling (All Samples) table for the top stall locations in your source based on
          sampling data. The Profiling Guide
          (https://docs.nvidia.com/nsight-compute/ProfilingGuide/index.html#metrics-reference) provides more details
          on each stall reason.

    Section: Instruction Statistics
    ---------------------------------------- ----------- ------------
    Metric Name                              Metric Unit Metric Value
    ---------------------------------------- ----------- ------------
    Avg. Executed Instructions Per Scheduler        inst        3,072
    Executed Instructions                           inst      491,520
    Avg. Issued Instructions Per Scheduler          inst        3,096
    Issued Instructions                             inst      495,360
    ---------------------------------------- ----------- ------------

    OPT   Est. Speedup: 3.79%
          This kernel executes 0 fused and 32768 non-fused FP32 instructions. By converting pairs of non-fused
          instructions to their fused (https://docs.nvidia.com/cuda/floating-point/#cuda-and-floating-point),
          higher-throughput equivalent, the achieved FP32 performance could be increased by up to 50% (relative to its
          current performance).

    Section: Launch Statistics
    -------------------------------- --------------- ---------------
    Metric Name                          Metric Unit    Metric Value
    -------------------------------- --------------- ---------------
    Block Size                                                   256
    Function Cache Configuration                     CachePreferNone
    Grid Size                                                  4,096
    Registers Per Thread             register/thread              16
    Shared Memory Configuration Size           Kbyte           32.77
    Driver Shared Memory Per Block        byte/block               0
    Dynamic Shared Memory Per Block       byte/block               0
    Static Shared Memory Per Block        byte/block               0
    # SMs                                         SM              40
    Stack Size                                                 1,024
    Threads                                   thread       1,048,576
    # TPCs                                                        20
    Enabled TPC IDs                                              all
    Uses Green Context                                             0
    Waves Per SM                                               25.60
    -------------------------------- --------------- ---------------

    Section: Occupancy
    ------------------------------- ----------- ------------
    Metric Name                     Metric Unit Metric Value
    ------------------------------- ----------- ------------
    Block Limit SM                        block           16
    Block Limit Registers                 block           16
    Block Limit Shared Mem                block           16
    Block Limit Warps                     block            4
    Theoretical Active Warps per SM        warp           32
    Theoretical Occupancy                     %          100
    Achieved Occupancy                        %        79.92
    Achieved Active Warps Per SM           warp        25.57
    ------------------------------- ----------- ------------

    OPT   Est. Speedup: 9.668%
          The difference between calculated theoretical (100.0%) and measured achieved occupancy (79.9%) can be the
          result of warp scheduling overheads or workload imbalances during the kernel execution. Load imbalances can
          occur between warps within a block as well as across blocks of the same kernel. See the CUDA Best Practices
          Guide (https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#occupancy) for more details on
          optimizing occupancy.

    Section: GPU and Memory Workload Distribution
    -------------------------- ----------- ------------
    Metric Name                Metric Unit Metric Value
    -------------------------- ----------- ------------
    Average DRAM Active Cycles       cycle   208,125.50
    Total DRAM Elapsed Cycles        cycle    1,843,200
    Average L1 Active Cycles         cycle    25,422.78
    Total L1 Elapsed Cycles          cycle    1,080,640
    Average L2 Active Cycles         cycle    36,770.09
    Total L2 Elapsed Cycles          cycle    1,381,088
    Average SM Active Cycles         cycle    25,422.78
    Total SM Elapsed Cycles          cycle    1,080,640
    Average SMSP Active Cycles       cycle    25,345.14
    Total SMSP Elapsed Cycles        cycle    4,322,560
    -------------------------- ----------- ------------

    Section: Source Counters
    ------------------------- ----------- ------------
    Metric Name               Metric Unit Metric Value
    ------------------------- ----------- ------------
    Branch Instructions Ratio           %         0.13
    Branch Instructions              inst       65,536
    Branch Efficiency                   %            0
    Avg. Divergent Branches      branches            0
    ------------------------- ----------- ------------

In [46]:
!ncu --list-sections

-------------------------------------------- ----------------------------------------------------------------- ------- --------------------------------------------------
Identifier                                   Display Name                                                      Enabled Filename
-------------------------------------------- ----------------------------------------------------------------- ------- --------------------------------------------------
C2CLink                                      C2CLink                                                           no      ...sight Compute/2025.3.1/Sections/C2CLink.section
ComputeWorkloadAnalysis                      Compute Workload Analysis                                         no      ...25.3.1/Sections/ComputeWorkloadAnalysis.section
InstructionStats                             Instruction Statistics                                            no      ...2025.3.1/Sections/InstructionStatistics.section
LaunchStats                                  Launch Statistics                                                 yes     ...pute/2025.3.1/Sections/LaunchStatistics.section
MemoryWorkloadAnalysis                       Memory Workload Analysis                                          no      ...025.3.1/Sections/MemoryWorkloadAnalysis.section
MemoryWorkloadAnalysis_Chart                 Memory Workload Analysis Chart                                    no      ...1/Sections/MemoryWorkloadAnalysis_Chart.section
MemoryWorkloadAnalysis_Tables                Memory Workload Analysis Tables                                   no      .../Sections/MemoryWorkloadAnalysis_Tables.section
NumaAffinity                                 NUMA Affinity                                                     no      ... Compute/2025.3.1/Sections/NumaAffinity.section
Nvlink                                       NVLink                                                            no      ...Nsight Compute/2025.3.1/Sections/Nvlink.section
Nvlink_Tables                                NVLink Tables                                                     no      ...Compute/2025.3.1/Sections/Nvlink_Tables.section
Nvlink_Topology                              NVLink Topology                                                   no      ...mpute/2025.3.1/Sections/Nvlink_Topology.section
Occupancy                                    Occupancy                                                         yes     ...ght Compute/2025.3.1/Sections/Occupancy.section
PmSampling                                   PM Sampling                                                       no      ...ht Compute/2025.3.1/Sections/PmSampling.section
PmSampling_WarpStates                        PM Sampling: Warp States                                          no      ...2025.3.1/Sections/PmSampling_WarpStates.section
SchedulerStats                               Scheduler Statistics                                              no      ...e/2025.3.1/Sections/SchedulerStatistics.section
SourceCounters                               Source Counters                                                   no      ...ompute/2025.3.1/Sections/SourceCounters.section
SpeedOfLight                                 GPU Speed Of Light Throughput                                     yes     ... Compute/2025.3.1/Sections/SpeedOfLight.section
SpeedOfLight_HierarchicalDoubleRooflineChart GPU Speed Of Light Hierarchical Roofline Chart (Double Precision) no      ...OfLight_HierarchicalDoubleRooflineChart.section
SpeedOfLight_HierarchicalHalfRooflineChart   GPU Speed Of Light Hierarchical Roofline Chart (Half Precision)   no      ...edOfLight_HierarchicalHalfRooflineChart.section
SpeedOfLight_HierarchicalSingleRooflineChart GPU Speed Of Light Hierarchical Roofline Chart (Single Precision) no      ...OfLight_HierarchicalSingleRooflineChart.section
SpeedOfLight_HierarchicalTensorRooflineChart GPU Speed Of Light Hierarchical Roofline Chart (Tensor Core)      no      ...OfLight_HierarchicalTensorRooflineChart.section
SpeedOfLight_RooflineChart                   GPU Speed Of Light Roofline Chart                                 no      ...3.1/Sections/SpeedOfLight_RooflineChart.section
WarpStateStats                               Warp State Statistics                                             no      ...e/2025.3.1/Sections/WarpStateStatistics.section
WorkloadDistribution                         GPU and Memory Workload Distribution                              yes     .../2025.3.1/Sections/WorkloadDistribution.section

In [47]:
!ncu --list-rules

------------------------ --------------------------- ------------------------------ --------------------------------------------------
Identifier               Display Name                Description                    Filename
------------------------ --------------------------- ------------------------------ --------------------------------------------------
AchievedOccupancy        Achieved Occupancy          Analysis of the Achieved       ... Compute/2025.3.1/Sections/AchievedOccupancy.py
                                                     Occupancy
CPIStall                 Warp Stall                  Warp stall analysis            ...IA Nsight Compute/2025.3.1/Sections/CPIStall.py
Compute                  Compute Bottleneck          Detect bottlenecks arising     ...DIA Nsight Compute/2025.3.1/Sections/Compute.py
                                                     from compute capabilities
FPInstructions           FP32/64 Instructions        Floating-point instruction     ...ght Compute/2025.3.1/Sections/FPInstructions.py
                                                     analysis.
HighPipeUtilization      High Pipe Utilization       High pipe utilization          ...ompute/2025.3.1/Sections/HighPipeUtilization.py
                                                     bottleneck analysis
IssueSlotUtilization     Issue Slot Utilization      Scheduler instruction issue    ...mpute/2025.3.1/Sections/IssueSlotUtilization.py
                                                     analysis
LaunchConfiguration      Launch Configuration        Kernel launch configuration    ...t Compute/2025.3.1/Sections/LaunchStatistics.py
                                                     analysis
Memory                   Memory Bottleneck           Detect bottlenecks arising     ...IDIA Nsight Compute/2025.3.1/Sections/Memory.py
                                                     from memory capabilities
MemoryApertureUsage      Memory Aperture Usage       Detection of frequent memory   ...ompute/2025.3.1/Sections/MemoryApertureUsage.py
                                                     accesses backed by apertures
                                                     with slower memory bandwidth
                                                     and higher latency.
MemoryCacheAccessPattern Memory Cache Access Pattern Detection of inefficient       ...e/2025.3.1/Sections/MemoryCacheAccessPattern.py
                                                     memory access patterns in
                                                     the L1/TEX and L2 caches.
MemoryL2Compression      Memory L2 Compression       Detection of inefficient use   ...ompute/2025.3.1/Sections/MemoryL2Compression.py
                                                     of L2 Compute Data
                                                     Compression
PCSamplingData           PC sampling data            PC sampling data               ...ght Compute/2025.3.1/Sections/PCSamplingData.py
PMSamplingData           PM Sampling Data            Detection of PM sampling data  ...ght Compute/2025.3.1/Sections/PMSamplingData.py
                                                     collection issues
SOLBottleneck            Bottleneck                  High-level bottleneck          ...sight Compute/2025.3.1/Sections/SpeedOfLight.py
                                                     detection
SOLFPRoofline            Roofline Analysis           Floating Point Roofline        ...pute/2025.3.1/Sections/SpeedOfLight_Roofline.py
                                                     Analysis
SharedMemoryConflicts    Shared Memory Conflicts     Detection of shared memory     ...pute/2025.3.1/Sections/SharedMemoryConflicts.py
                                                     bank conflicts.
SlowPipeLimiter          Slow Pipe Limiter           Slow pipe limiting compute     ...ht Compute/2025.3.1/Sections/SlowPipeLimiter.py
                                                     utilization
TheoreticalOccupancy     Theoretical Occupancy       Analysis of Theoretical        ...mpute/2025.3.1/Sections/TheoreticalOccupancy.py
                                                     Occupancy and its Limiters
ThreadDivergence         Thread Divergence           Warp and thread control flow   ...t Compute/2025.3.1/Sections/ThreadDivergence.py
                                                     analysis
UncoalescedGlobalAccess  Uncoalesced Global Accesses Uncoalesced Global Accesses    ... Compute/2025.3.1/Sections/UncoalescedAccess.py
UncoalescedSharedAccess  Uncoalesced Shared Accesses Uncoalesced Shared Accesses    ...te/2025.3.1/Sections/UncoalescedSharedAccess.py
WorkloadImbalance        Workload Imbalance          Analysis of workload           ... Compute/2025.3.1/Sections/WorkloadImbalance.py
                                                     distribution in active
                                                     cycles of SM, SMP, SMSP, L1
                                                     & L2 caches, and DRAM

In [56]:
!ncu --list-metrics

smsp__warps_active.sum.peak_sustained
 -smsp__warps_active.sum.peak_sustained
smsp__warps_active.min.peak_sustained
 -smsp__warps_active.min.peak_sustained
smsp__warps_active.max.peak_sustained
 -smsp__warps_active.max.peak_sustained
smsp__warps_active.avg.peak_sustained
 -smsp__warps_active.avg.peak_sustained
smsp__maximum_warps_avg_per_active_cycle
 -smsp__maximum_warps_avg_per_active_cycle
smsp__cycles_elapsed.sum
 -smsp__cycles_elapsed.sum
smsp__cycles_elapsed.min
 -smsp__cycles_elapsed.min
smsp__cycles_elapsed.max
 -smsp__cycles_elapsed.max
smsp__cycles_elapsed.avg
 -smsp__cycles_elapsed.avg
smsp__cycles_active.sum
 -smsp__cycles_active.sum
smsp__cycles_active.min
 -smsp__cycles_active.min
smsp__cycles_active.max
 -smsp__cycles_active.max
smsp__cycles_active.avg
 -smsp__cycles_active.avg
sm__warps_active.sum.per_cycle_active
 -sm__warps_active.sum.per_cycle_active
sm__warps_active.sum.pct_of_peak_sustained_active
 -sm__warps_active.sum.pct_of_peak_sustained_active
sm__warps_active.min.per_cycle_active
 -sm__warps_active.min.per_cycle_active
sm__warps_active.min.pct_of_peak_sustained_active
 -sm__warps_active.min.pct_of_peak_sustained_active
sm__warps_active.max.per_cycle_active
 -sm__warps_active.max.per_cycle_active
sm__warps_active.max.pct_of_peak_sustained_active
 -sm__warps_active.max.pct_of_peak_sustained_active
sm__warps_active.avg.per_cycle_active
 -sm__warps_active.avg.per_cycle_active
sm__warps_active.avg.pct_of_peak_sustained_active
 -sm__warps_active.avg.pct_of_peak_sustained_active
sm__throughput.sum.pct_of_peak_sustained_elapsed
 -sm__throughput.sum.pct_of_peak_sustained_elapsed
sm__throughput.min.pct_of_peak_sustained_elapsed
 -sm__throughput.min.pct_of_peak_sustained_elapsed
sm__throughput.max.pct_of_peak_sustained_elapsed
 -sm__throughput.max.pct_of_peak_sustained_elapsed
sm__throughput.avg.pct_of_peak_sustained_elapsed
 -sm__throughput.avg.pct_of_peak_sustained_elapsed
sm__maximum_warps_per_active_cycle_pct
 -sm__maximum_warps_per_active_cycle_pct
sm__maximum_warps_avg_per_active_cycle
 -sm__maximum_warps_avg_per_active_cycle
sm__cycles_elapsed.sum
 -sm__cycles_elapsed.sum
sm__cycles_elapsed.min
 -sm__cycles_elapsed.min
sm__cycles_elapsed.max
 -sm__cycles_elapsed.max
sm__cycles_elapsed.avg
 -sm__cycles_elapsed.avg
sm__cycles_active.sum
 -sm__cycles_active.sum
sm__cycles_active.min
 -sm__cycles_active.min
sm__cycles_active.max
 -sm__cycles_active.max
sm__cycles_active.avg
 -sm__cycles_active.avg
lts__throughput.sum.pct_of_peak_sustained_elapsed
 -lts__throughput.sum.pct_of_peak_sustained_elapsed
lts__throughput.min.pct_of_peak_sustained_elapsed
 -lts__throughput.min.pct_of_peak_sustained_elapsed
lts__throughput.max.pct_of_peak_sustained_elapsed
 -lts__throughput.max.pct_of_peak_sustained_elapsed
lts__throughput.avg.pct_of_peak_sustained_elapsed
 -lts__throughput.avg.pct_of_peak_sustained_elapsed
lts__cycles_elapsed.sum
 -lts__cycles_elapsed.sum
lts__cycles_elapsed.min
 -lts__cycles_elapsed.min
lts__cycles_elapsed.max
 -lts__cycles_elapsed.max
lts__cycles_elapsed.avg
 -lts__cycles_elapsed.avg
lts__cycles_active.sum
 -lts__cycles_active.sum
lts__cycles_active.min
 -lts__cycles_active.min
lts__cycles_active.max
 -lts__cycles_active.max
lts__cycles_active.avg
 -lts__cycles_active.avg
launch__waves_per_multiprocessor
 -launch__waves_per_multiprocessor
launch__uses_green_context
 -launch__uses_green_context
launch__tpc_enabled
 -launch__tpc_enabled
launch__tpc_count
 -launch__tpc_count
launch__thread_count
 -launch__thread_count
launch__stack_size
 -launch__stack_size
launch__sm_count
 -launch__sm_count
launch__shared_mem_per_block_static
 -launch__shared_mem_per_block_static
launch__shared_mem_per_block_dynamic
 -launch__shared_mem_per_block_dynamic
launch__shared_mem_per_block_driver
 -launch__shared_mem_per_block_driver
launch__shared_mem_per_block
 -launch__shared_mem_per_block
launch__shared_mem_config_size
 -launch__shared_mem_config_size
launch__registers_per_thread
 -launch__registers_per_thread
launch__occupancy_per_shared_mem_size
 -launch__occupancy_per_shared_mem_size
launch__occupancy_per_register_count
 -launch__occupancy_per_register_count
launch__occupancy_per_block_size
 -launch__occupancy_per_block_size
launch__occupancy_limit_warps
 -launch__occupancy_limit_warps
launch__occupancy_limit_shared_mem
 -launch__occupancy_limit_shared_mem
launch__occupancy_limit_registers
 -launch__occupancy_limit_registers
launch__occupancy_limit_blocks
 -launch__occupancy_limit_blocks
launch__grid_size
 -launch__grid_size
launch__func_cache_config
 -launch__func_cache_config
launch__block_size
 -launch__block_size
l1tex__throughput.sum.pct_of_peak_sustained_active
 -l1tex__throughput.sum.pct_of_peak_sustained_active
l1tex__throughput.min.pct_of_peak_sustained_active
 -l1tex__throughput.min.pct_of_peak_sustained_active
l1tex__throughput.max.pct_of_peak_sustained_active
 -l1tex__throughput.max.pct_of_peak_sustained_active
l1tex__throughput.avg.pct_of_peak_sustained_active
 -l1tex__throughput.avg.pct_of_peak_sustained_active
l1tex__cycles_elapsed.sum
 -l1tex__cycles_elapsed.sum
l1tex__cycles_elapsed.min
 -l1tex__cycles_elapsed.min
l1tex__cycles_elapsed.max
 -l1tex__cycles_elapsed.max
l1tex__cycles_elapsed.avg
 -l1tex__cycles_elapsed.avg
l1tex__cycles_active.sum
 -l1tex__cycles_active.sum
l1tex__cycles_active.min
 -l1tex__cycles_active.min
l1tex__cycles_active.max
 -l1tex__cycles_active.max
l1tex__cycles_active.avg
 -l1tex__cycles_active.avg
gpu__time_duration.sum
 -gpu__time_duration.sum
gpu__time_duration.min
 -gpu__time_duration.min
gpu__time_duration.max
 -gpu__time_duration.max
gpu__time_duration.avg
 -gpu__time_duration.avg
gpu__compute_memory_throughput.sum.pct_of_peak_sustained_elapsed
 -gpu__compute_memory_throughput.sum.pct_of_peak_sustained_elapsed
gpu__compute_memory_throughput.min.pct_of_peak_sustained_elapsed
 -gpu__compute_memory_throughput.min.pct_of_peak_sustained_elapsed
gpu__compute_memory_throughput.max.pct_of_peak_sustained_elapsed
 -gpu__compute_memory_throughput.max.pct_of_peak_sustained_elapsed
gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed
 -gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed
gpc__cycles_elapsed.sum.per_second
 -gpc__cycles_elapsed.sum.per_second
gpc__cycles_elapsed.sum
 -gpc__cycles_elapsed.sum
gpc__cycles_elapsed.min.per_second
 -gpc__cycles_elapsed.min.per_second
gpc__cycles_elapsed.min
 -gpc__cycles_elapsed.min
gpc__cycles_elapsed.max.per_second
 -gpc__cycles_elapsed.max.per_second
gpc__cycles_elapsed.max
 -gpc__cycles_elapsed.max
gpc__cycles_elapsed.avg.per_second
 -gpc__cycles_elapsed.avg.per_second
gpc__cycles_elapsed.avg
 -gpc__cycles_elapsed.avg
derived__pct_occupancy_per_shared_mem_size
 -derived__pct_occupancy_per_shared_mem_size
derived__pct_occupancy_per_register_count
 -derived__pct_occupancy_per_register_count
derived__pct_occupancy_per_block_size
 -derived__pct_occupancy_per_block_size
breakdown:sm__throughput.sum.pct_of_peak_sustained_elapsed
 -breakdown:sm__throughput.sum.pct_of_peak_sustained_elapsed
breakdown:sm__throughput.min.pct_of_peak_sustained_elapsed
 -breakdown:sm__throughput.min.pct_of_peak_sustained_elapsed
breakdown:sm__throughput.max.pct_of_peak_sustained_elapsed
 -breakdown:sm__throughput.max.pct_of_peak_sustained_elapsed
breakdown:sm__throughput.avg.pct_of_peak_sustained_elapsed
 -breakdown:sm__throughput.avg.pct_of_peak_sustained_elapsed
breakdown:gpu__compute_memory_throughput.sum.pct_of_peak_sustained_elapsed
 -breakdown:gpu__compute_memory_throughput.sum.pct_of_peak_sustained_elapsed
breakdown:gpu__compute_memory_throughput.min.pct_of_peak_sustained_elapsed
 -breakdown:gpu__compute_memory_throughput.min.pct_of_peak_sustained_elapsed
breakdown:gpu__compute_memory_throughput.max.pct_of_peak_sustained_elapsed
 -breakdown:gpu__compute_memory_throughput.max.pct_of_peak_sustained_elapsed
breakdown:gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed
 -breakdown:gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed
launch__occupancy_per_cluster_size
 -arch:90:121:launch__occupancy_per_cluster_size
launch__occupancy_per_barrier_count
 -arch:90:121:launch__occupancy_per_barrier_count
launch__occupancy_limit_barriers
 -arch:90:121:launch__occupancy_limit_barriers
launch__occupancy_cluster_pct
 -arch:90:121:launch__occupancy_cluster_pct
launch__occupancy_cluster_gpu_pct
 -arch:90:121:launch__occupancy_cluster_gpu_pct
launch__cluster_size
 -arch:90:121:launch__cluster_size
launch__cluster_scheduling_policy
 -arch:90:121:launch__cluster_scheduling_policy
launch__cluster_max_potential_size
 -arch:90:121:launch__cluster_max_potential_size
launch__cluster_max_active
 -arch:90:121:launch__cluster_max_active
launch__barrier_count
 -arch:90:121:launch__barrier_count
derived__pct_occupancy_per_barrier_count
 -arch:90:121:derived__pct_occupancy_per_barrier_count
gpu__dram_throughput.sum.pct_of_peak_sustained_elapsed
 -arch:120:120:gpu__dram_throughput.sum.pct_of_peak_sustained_elapsed
 -arch:103:103:gpu__dram_throughput.sum.pct_of_peak_sustained_elapsed
 -arch:89:100:gpu__dram_throughput.sum.pct_of_peak_sustained_elapsed
 -arch:75:86:gpu__dram_throughput.sum.pct_of_peak_sustained_elapsed
gpu__dram_throughput.min.pct_of_peak_sustained_elapsed
 -arch:120:120:gpu__dram_throughput.min.pct_of_peak_sustained_elapsed
 -arch:103:103:gpu__dram_throughput.min.pct_of_peak_sustained_elapsed
 -arch:89:100:gpu__dram_throughput.min.pct_of_peak_sustained_elapsed
 -arch:75:86:gpu__dram_throughput.min.pct_of_peak_sustained_elapsed
gpu__dram_throughput.max.pct_of_peak_sustained_elapsed
 -arch:120:120:gpu__dram_throughput.max.pct_of_peak_sustained_elapsed
 -arch:103:103:gpu__dram_throughput.max.pct_of_peak_sustained_elapsed
 -arch:89:100:gpu__dram_throughput.max.pct_of_peak_sustained_elapsed
 -arch:75:86:gpu__dram_throughput.max.pct_of_peak_sustained_elapsed
gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed
 -arch:120:120:gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed
 -arch:103:103:gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed
 -arch:89:100:gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed
 -arch:75:86:gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed
dram__cycles_elapsed.sum
 -arch:120:120:dram__cycles_elapsed.sum
 -arch:103:103:dram__cycles_elapsed.sum
 -arch:89:100:dram__cycles_elapsed.sum
 -arch:75:86:dram__cycles_elapsed.sum
dram__cycles_elapsed.sum.per_second
 -arch:120:120:dram__cycles_elapsed.sum.per_second
 -arch:103:103:dram__cycles_elapsed.sum.per_second
 -arch:89:100:dram__cycles_elapsed.sum.per_second
 -arch:75:86:dram__cycles_elapsed.sum.per_second
dram__cycles_elapsed.min
 -arch:120:120:dram__cycles_elapsed.min
 -arch:103:103:dram__cycles_elapsed.min
 -arch:89:100:dram__cycles_elapsed.min
 -arch:75:86:dram__cycles_elapsed.min
dram__cycles_elapsed.min.per_second
 -arch:120:120:dram__cycles_elapsed.min.per_second
 -arch:103:103:dram__cycles_elapsed.min.per_second
 -arch:89:100:dram__cycles_elapsed.min.per_second
 -arch:75:86:dram__cycles_elapsed.min.per_second
dram__cycles_elapsed.max
 -arch:120:120:dram__cycles_elapsed.max
 -arch:103:103:dram__cycles_elapsed.max
 -arch:89:100:dram__cycles_elapsed.max
 -arch:75:86:dram__cycles_elapsed.max
dram__cycles_elapsed.max.per_second
 -arch:120:120:dram__cycles_elapsed.max.per_second
 -arch:103:103:dram__cycles_elapsed.max.per_second
 -arch:89:100:dram__cycles_elapsed.max.per_second
 -arch:75:86:dram__cycles_elapsed.max.per_second
dram__cycles_elapsed.avg
 -arch:120:120:dram__cycles_elapsed.avg
 -arch:103:103:dram__cycles_elapsed.avg
 -arch:89:100:dram__cycles_elapsed.avg
 -arch:75:86:dram__cycles_elapsed.avg
dram__cycles_elapsed.avg.per_second
 -arch:120:120:dram__cycles_elapsed.avg.per_second
 -arch:103:103:dram__cycles_elapsed.avg.per_second
 -arch:89:100:dram__cycles_elapsed.avg.per_second
 -arch:75:86:dram__cycles_elapsed.avg.per_second
dram__cycles_active.sum
 -arch:120:120:dram__cycles_active.sum
 -arch:103:103:dram__cycles_active.sum
 -arch:89:100:dram__cycles_active.sum
 -arch:75:86:dram__cycles_active.sum
dram__cycles_active.min
 -arch:120:120:dram__cycles_active.min
 -arch:103:103:dram__cycles_active.min
 -arch:89:100:dram__cycles_active.min
 -arch:75:86:dram__cycles_active.min
dram__cycles_active.max
 -arch:120:120:dram__cycles_active.max
 -arch:103:103:dram__cycles_active.max
 -arch:89:100:dram__cycles_active.max
 -arch:75:86:dram__cycles_active.max
dram__cycles_active.avg
 -arch:120:120:dram__cycles_active.avg
 -arch:103:103:dram__cycles_active.avg
 -arch:89:100:dram__cycles_active.avg
 -arch:75:86:dram__cycles_active.avg
mcc__cycles_elapsed.sum
 -arch:110:110:mcc__cycles_elapsed.sum
 -arch:87:87:mcc__cycles_elapsed.sum
mcc__cycles_elapsed.min
 -arch:110:110:mcc__cycles_elapsed.min
 -arch:87:87:mcc__cycles_elapsed.min
mcc__cycles_elapsed.max
 -arch:110:110:mcc__cycles_elapsed.max
 -arch:87:87:mcc__cycles_elapsed.max
mcc__cycles_elapsed.avg
 -arch:110:110:mcc__cycles_elapsed.avg
 -arch:87:87:mcc__cycles_elapsed.avg
mcc__cycles_active.sum
 -arch:110:110:mcc__cycles_active.sum
 -arch:87:87:mcc__cycles_active.sum
mcc__cycles_active.min
 -arch:110:110:mcc__cycles_active.min
 -arch:87:87:mcc__cycles_active.min
mcc__cycles_active.max
 -arch:110:110:mcc__cycles_active.max
 -arch:87:87:mcc__cycles_active.max
mcc__cycles_active.avg
 -arch:110:110:mcc__cycles_active.avg
 -arch:87:87:mcc__cycles_active.avg
launch__preferred_cluster_size
 -arch:100:121:launch__preferred_cluster_size
gr__workids_requested.sum
 -arch:100:121:gr__workids_requested.sum
gr__workids_requested.min
 -arch:100:121:gr__workids_requested.min
gr__workids_requested.max
 -arch:100:121:gr__workids_requested.max
gr__workids_requested.avg
 -arch:100:121:gr__workids_requested.avg
gr__workids_granted_as_ctas.sum
 -arch:100:121:gr__workids_granted_as_ctas.sum
gr__workids_granted_as_ctas.min
 -arch:100:121:gr__workids_granted_as_ctas.min
gr__workids_granted_as_ctas.max
 -arch:100:121:gr__workids_granted_as_ctas.max
gr__workids_granted_as_ctas.avg
 -arch:100:121:gr__workids_granted_as_ctas.avg
gr__workids_granted.sum
 -arch:100:121:gr__workids_granted.sum
gr__workids_granted.min
 -arch:100:121:gr__workids_granted.min
gr__workids_granted.max
 -arch:100:121:gr__workids_granted.max
gr__workids_granted.avg
 -arch:100:121:gr__workids_granted.avg

https://docs.nvidia.com/nsight-compute/ProfilingGuide/index.html?utm_source=chatgpt.com#metrics-reference

ncu list metrics, but basic mode

In [63]:
!ncu --set basic --list-metrics

smsp__warps_active.sum.peak_sustained
 -smsp__warps_active.sum.peak_sustained
smsp__warps_active.min.peak_sustained
 -smsp__warps_active.min.peak_sustained
smsp__warps_active.max.peak_sustained
 -smsp__warps_active.max.peak_sustained
smsp__warps_active.avg.peak_sustained
 -smsp__warps_active.avg.peak_sustained
smsp__maximum_warps_avg_per_active_cycle
 -smsp__maximum_warps_avg_per_active_cycle
smsp__cycles_elapsed.sum
 -smsp__cycles_elapsed.sum
smsp__cycles_elapsed.min
 -smsp__cycles_elapsed.min
smsp__cycles_elapsed.max
 -smsp__cycles_elapsed.max
smsp__cycles_elapsed.avg
 -smsp__cycles_elapsed.avg
smsp__cycles_active.sum
 -smsp__cycles_active.sum
smsp__cycles_active.min
 -smsp__cycles_active.min
smsp__cycles_active.max
 -smsp__cycles_active.max
smsp__cycles_active.avg
 -smsp__cycles_active.avg
sm__warps_active.sum.per_cycle_active
 -sm__warps_active.sum.per_cycle_active
sm__warps_active.sum.pct_of_peak_sustained_active
 -sm__warps_active.sum.pct_of_peak_sustained_active
sm__warps_active.min.per_cycle_active
 -sm__warps_active.min.per_cycle_active
sm__warps_active.min.pct_of_peak_sustained_active
 -sm__warps_active.min.pct_of_peak_sustained_active
sm__warps_active.max.per_cycle_active
 -sm__warps_active.max.per_cycle_active
sm__warps_active.max.pct_of_peak_sustained_active
 -sm__warps_active.max.pct_of_peak_sustained_active
sm__warps_active.avg.per_cycle_active
 -sm__warps_active.avg.per_cycle_active
sm__warps_active.avg.pct_of_peak_sustained_active
 -sm__warps_active.avg.pct_of_peak_sustained_active
sm__throughput.sum.pct_of_peak_sustained_elapsed
 -sm__throughput.sum.pct_of_peak_sustained_elapsed
sm__throughput.min.pct_of_peak_sustained_elapsed
 -sm__throughput.min.pct_of_peak_sustained_elapsed
sm__throughput.max.pct_of_peak_sustained_elapsed
 -sm__throughput.max.pct_of_peak_sustained_elapsed
sm__throughput.avg.pct_of_peak_sustained_elapsed
 -sm__throughput.avg.pct_of_peak_sustained_elapsed
sm__maximum_warps_per_active_cycle_pct
 -sm__maximum_warps_per_active_cycle_pct
sm__maximum_warps_avg_per_active_cycle
 -sm__maximum_warps_avg_per_active_cycle
sm__cycles_elapsed.sum
 -sm__cycles_elapsed.sum
sm__cycles_elapsed.min
 -sm__cycles_elapsed.min
sm__cycles_elapsed.max
 -sm__cycles_elapsed.max
sm__cycles_elapsed.avg
 -sm__cycles_elapsed.avg
sm__cycles_active.sum
 -sm__cycles_active.sum
sm__cycles_active.min
 -sm__cycles_active.min
sm__cycles_active.max
 -sm__cycles_active.max
sm__cycles_active.avg
 -sm__cycles_active.avg
lts__throughput.sum.pct_of_peak_sustained_elapsed
 -lts__throughput.sum.pct_of_peak_sustained_elapsed
lts__throughput.min.pct_of_peak_sustained_elapsed
 -lts__throughput.min.pct_of_peak_sustained_elapsed
lts__throughput.max.pct_of_peak_sustained_elapsed
 -lts__throughput.max.pct_of_peak_sustained_elapsed
lts__throughput.avg.pct_of_peak_sustained_elapsed
 -lts__throughput.avg.pct_of_peak_sustained_elapsed
lts__cycles_elapsed.sum
 -lts__cycles_elapsed.sum
lts__cycles_elapsed.min
 -lts__cycles_elapsed.min
lts__cycles_elapsed.max
 -lts__cycles_elapsed.max
lts__cycles_elapsed.avg
 -lts__cycles_elapsed.avg
lts__cycles_active.sum
 -lts__cycles_active.sum
lts__cycles_active.min
 -lts__cycles_active.min
lts__cycles_active.max
 -lts__cycles_active.max
lts__cycles_active.avg
 -lts__cycles_active.avg
launch__waves_per_multiprocessor
 -launch__waves_per_multiprocessor
launch__uses_green_context
 -launch__uses_green_context
launch__tpc_enabled
 -launch__tpc_enabled
launch__tpc_count
 -launch__tpc_count
launch__thread_count
 -launch__thread_count
launch__stack_size
 -launch__stack_size
launch__sm_count
 -launch__sm_count
launch__shared_mem_per_block_static
 -launch__shared_mem_per_block_static
launch__shared_mem_per_block_dynamic
 -launch__shared_mem_per_block_dynamic
launch__shared_mem_per_block_driver
 -launch__shared_mem_per_block_driver
launch__shared_mem_per_block
 -launch__shared_mem_per_block
launch__shared_mem_config_size
 -launch__shared_mem_config_size
launch__registers_per_thread
 -launch__registers_per_thread
launch__occupancy_per_shared_mem_size
 -launch__occupancy_per_shared_mem_size
launch__occupancy_per_register_count
 -launch__occupancy_per_register_count
launch__occupancy_per_block_size
 -launch__occupancy_per_block_size
launch__occupancy_limit_warps
 -launch__occupancy_limit_warps
launch__occupancy_limit_shared_mem
 -launch__occupancy_limit_shared_mem
launch__occupancy_limit_registers
 -launch__occupancy_limit_registers
launch__occupancy_limit_blocks
 -launch__occupancy_limit_blocks
launch__grid_size
 -launch__grid_size
launch__func_cache_config
 -launch__func_cache_config
launch__block_size
 -launch__block_size
l1tex__throughput.sum.pct_of_peak_sustained_active
 -l1tex__throughput.sum.pct_of_peak_sustained_active
l1tex__throughput.min.pct_of_peak_sustained_active
 -l1tex__throughput.min.pct_of_peak_sustained_active
l1tex__throughput.max.pct_of_peak_sustained_active
 -l1tex__throughput.max.pct_of_peak_sustained_active
l1tex__throughput.avg.pct_of_peak_sustained_active
 -l1tex__throughput.avg.pct_of_peak_sustained_active
l1tex__cycles_elapsed.sum
 -l1tex__cycles_elapsed.sum
l1tex__cycles_elapsed.min
 -l1tex__cycles_elapsed.min
l1tex__cycles_elapsed.max
 -l1tex__cycles_elapsed.max
l1tex__cycles_elapsed.avg
 -l1tex__cycles_elapsed.avg
l1tex__cycles_active.sum
 -l1tex__cycles_active.sum
l1tex__cycles_active.min
 -l1tex__cycles_active.min
l1tex__cycles_active.max
 -l1tex__cycles_active.max
l1tex__cycles_active.avg
 -l1tex__cycles_active.avg
gpu__time_duration.sum
 -gpu__time_duration.sum
gpu__time_duration.min
 -gpu__time_duration.min
gpu__time_duration.max
 -gpu__time_duration.max
gpu__time_duration.avg
 -gpu__time_duration.avg
gpu__compute_memory_throughput.sum.pct_of_peak_sustained_elapsed
 -gpu__compute_memory_throughput.sum.pct_of_peak_sustained_elapsed
gpu__compute_memory_throughput.min.pct_of_peak_sustained_elapsed
 -gpu__compute_memory_throughput.min.pct_of_peak_sustained_elapsed
gpu__compute_memory_throughput.max.pct_of_peak_sustained_elapsed
 -gpu__compute_memory_throughput.max.pct_of_peak_sustained_elapsed
gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed
 -gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed
gpc__cycles_elapsed.sum.per_second
 -gpc__cycles_elapsed.sum.per_second
gpc__cycles_elapsed.sum
 -gpc__cycles_elapsed.sum
gpc__cycles_elapsed.min.per_second
 -gpc__cycles_elapsed.min.per_second
gpc__cycles_elapsed.min
 -gpc__cycles_elapsed.min
gpc__cycles_elapsed.max.per_second
 -gpc__cycles_elapsed.max.per_second
gpc__cycles_elapsed.max
 -gpc__cycles_elapsed.max
gpc__cycles_elapsed.avg.per_second
 -gpc__cycles_elapsed.avg.per_second
gpc__cycles_elapsed.avg
 -gpc__cycles_elapsed.avg
derived__pct_occupancy_per_shared_mem_size
 -derived__pct_occupancy_per_shared_mem_size
derived__pct_occupancy_per_register_count
 -derived__pct_occupancy_per_register_count
derived__pct_occupancy_per_block_size
 -derived__pct_occupancy_per_block_size
breakdown:sm__throughput.sum.pct_of_peak_sustained_elapsed
 -breakdown:sm__throughput.sum.pct_of_peak_sustained_elapsed
breakdown:sm__throughput.min.pct_of_peak_sustained_elapsed
 -breakdown:sm__throughput.min.pct_of_peak_sustained_elapsed
breakdown:sm__throughput.max.pct_of_peak_sustained_elapsed
 -breakdown:sm__throughput.max.pct_of_peak_sustained_elapsed
breakdown:sm__throughput.avg.pct_of_peak_sustained_elapsed
 -breakdown:sm__throughput.avg.pct_of_peak_sustained_elapsed
breakdown:gpu__compute_memory_throughput.sum.pct_of_peak_sustained_elapsed
 -breakdown:gpu__compute_memory_throughput.sum.pct_of_peak_sustained_elapsed
breakdown:gpu__compute_memory_throughput.min.pct_of_peak_sustained_elapsed
 -breakdown:gpu__compute_memory_throughput.min.pct_of_peak_sustained_elapsed
breakdown:gpu__compute_memory_throughput.max.pct_of_peak_sustained_elapsed
 -breakdown:gpu__compute_memory_throughput.max.pct_of_peak_sustained_elapsed
breakdown:gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed
 -breakdown:gpu__compute_memory_throughput.avg.pct_of_peak_sustained_elapsed
launch__occupancy_per_cluster_size
 -arch:90:121:launch__occupancy_per_cluster_size
launch__occupancy_per_barrier_count
 -arch:90:121:launch__occupancy_per_barrier_count
launch__occupancy_limit_barriers
 -arch:90:121:launch__occupancy_limit_barriers
launch__occupancy_cluster_pct
 -arch:90:121:launch__occupancy_cluster_pct
launch__occupancy_cluster_gpu_pct
 -arch:90:121:launch__occupancy_cluster_gpu_pct
launch__cluster_size
 -arch:90:121:launch__cluster_size
launch__cluster_scheduling_policy
 -arch:90:121:launch__cluster_scheduling_policy
launch__cluster_max_potential_size
 -arch:90:121:launch__cluster_max_potential_size
launch__cluster_max_active
 -arch:90:121:launch__cluster_max_active
launch__barrier_count
 -arch:90:121:launch__barrier_count
derived__pct_occupancy_per_barrier_count
 -arch:90:121:derived__pct_occupancy_per_barrier_count
gpu__dram_throughput.sum.pct_of_peak_sustained_elapsed
 -arch:120:120:gpu__dram_throughput.sum.pct_of_peak_sustained_elapsed
 -arch:103:103:gpu__dram_throughput.sum.pct_of_peak_sustained_elapsed
 -arch:89:100:gpu__dram_throughput.sum.pct_of_peak_sustained_elapsed
 -arch:75:86:gpu__dram_throughput.sum.pct_of_peak_sustained_elapsed
gpu__dram_throughput.min.pct_of_peak_sustained_elapsed
 -arch:120:120:gpu__dram_throughput.min.pct_of_peak_sustained_elapsed
 -arch:103:103:gpu__dram_throughput.min.pct_of_peak_sustained_elapsed
 -arch:89:100:gpu__dram_throughput.min.pct_of_peak_sustained_elapsed
 -arch:75:86:gpu__dram_throughput.min.pct_of_peak_sustained_elapsed
gpu__dram_throughput.max.pct_of_peak_sustained_elapsed
 -arch:120:120:gpu__dram_throughput.max.pct_of_peak_sustained_elapsed
 -arch:103:103:gpu__dram_throughput.max.pct_of_peak_sustained_elapsed
 -arch:89:100:gpu__dram_throughput.max.pct_of_peak_sustained_elapsed
 -arch:75:86:gpu__dram_throughput.max.pct_of_peak_sustained_elapsed
gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed
 -arch:120:120:gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed
 -arch:103:103:gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed
 -arch:89:100:gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed
 -arch:75:86:gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed
dram__cycles_elapsed.sum
 -arch:120:120:dram__cycles_elapsed.sum
 -arch:103:103:dram__cycles_elapsed.sum
 -arch:89:100:dram__cycles_elapsed.sum
 -arch:75:86:dram__cycles_elapsed.sum
dram__cycles_elapsed.sum.per_second
 -arch:120:120:dram__cycles_elapsed.sum.per_second
 -arch:103:103:dram__cycles_elapsed.sum.per_second
 -arch:89:100:dram__cycles_elapsed.sum.per_second
 -arch:75:86:dram__cycles_elapsed.sum.per_second
dram__cycles_elapsed.min
 -arch:120:120:dram__cycles_elapsed.min
 -arch:103:103:dram__cycles_elapsed.min
 -arch:89:100:dram__cycles_elapsed.min
 -arch:75:86:dram__cycles_elapsed.min
dram__cycles_elapsed.min.per_second
 -arch:120:120:dram__cycles_elapsed.min.per_second
 -arch:103:103:dram__cycles_elapsed.min.per_second
 -arch:89:100:dram__cycles_elapsed.min.per_second
 -arch:75:86:dram__cycles_elapsed.min.per_second
dram__cycles_elapsed.max
 -arch:120:120:dram__cycles_elapsed.max
 -arch:103:103:dram__cycles_elapsed.max
 -arch:89:100:dram__cycles_elapsed.max
 -arch:75:86:dram__cycles_elapsed.max
dram__cycles_elapsed.max.per_second
 -arch:120:120:dram__cycles_elapsed.max.per_second
 -arch:103:103:dram__cycles_elapsed.max.per_second
 -arch:89:100:dram__cycles_elapsed.max.per_second
 -arch:75:86:dram__cycles_elapsed.max.per_second
dram__cycles_elapsed.avg
 -arch:120:120:dram__cycles_elapsed.avg
 -arch:103:103:dram__cycles_elapsed.avg
 -arch:89:100:dram__cycles_elapsed.avg
 -arch:75:86:dram__cycles_elapsed.avg
dram__cycles_elapsed.avg.per_second
 -arch:120:120:dram__cycles_elapsed.avg.per_second
 -arch:103:103:dram__cycles_elapsed.avg.per_second
 -arch:89:100:dram__cycles_elapsed.avg.per_second
 -arch:75:86:dram__cycles_elapsed.avg.per_second
dram__cycles_active.sum
 -arch:120:120:dram__cycles_active.sum
 -arch:103:103:dram__cycles_active.sum
 -arch:89:100:dram__cycles_active.sum
 -arch:75:86:dram__cycles_active.sum
dram__cycles_active.min
 -arch:120:120:dram__cycles_active.min
 -arch:103:103:dram__cycles_active.min
 -arch:89:100:dram__cycles_active.min
 -arch:75:86:dram__cycles_active.min
dram__cycles_active.max
 -arch:120:120:dram__cycles_active.max
 -arch:103:103:dram__cycles_active.max
 -arch:89:100:dram__cycles_active.max
 -arch:75:86:dram__cycles_active.max
dram__cycles_active.avg
 -arch:120:120:dram__cycles_active.avg
 -arch:103:103:dram__cycles_active.avg
 -arch:89:100:dram__cycles_active.avg
 -arch:75:86:dram__cycles_active.avg
mcc__cycles_elapsed.sum
 -arch:110:110:mcc__cycles_elapsed.sum
 -arch:87:87:mcc__cycles_elapsed.sum
mcc__cycles_elapsed.min
 -arch:110:110:mcc__cycles_elapsed.min
 -arch:87:87:mcc__cycles_elapsed.min
mcc__cycles_elapsed.max
 -arch:110:110:mcc__cycles_elapsed.max
 -arch:87:87:mcc__cycles_elapsed.max
mcc__cycles_elapsed.avg
 -arch:110:110:mcc__cycles_elapsed.avg
 -arch:87:87:mcc__cycles_elapsed.avg
mcc__cycles_active.sum
 -arch:110:110:mcc__cycles_active.sum
 -arch:87:87:mcc__cycles_active.sum
mcc__cycles_active.min
 -arch:110:110:mcc__cycles_active.min
 -arch:87:87:mcc__cycles_active.min
mcc__cycles_active.max
 -arch:110:110:mcc__cycles_active.max
 -arch:87:87:mcc__cycles_active.max
mcc__cycles_active.avg
 -arch:110:110:mcc__cycles_active.avg
 -arch:87:87:mcc__cycles_active.avg
launch__preferred_cluster_size
 -arch:100:121:launch__preferred_cluster_size
gr__workids_requested.sum
 -arch:100:121:gr__workids_requested.sum
gr__workids_requested.min
 -arch:100:121:gr__workids_requested.min
gr__workids_requested.max
 -arch:100:121:gr__workids_requested.max
gr__workids_requested.avg
 -arch:100:121:gr__workids_requested.avg
gr__workids_granted_as_ctas.sum
 -arch:100:121:gr__workids_granted_as_ctas.sum
gr__workids_granted_as_ctas.min
 -arch:100:121:gr__workids_granted_as_ctas.min
gr__workids_granted_as_ctas.max
 -arch:100:121:gr__workids_granted_as_ctas.max
gr__workids_granted_as_ctas.avg
 -arch:100:121:gr__workids_granted_as_ctas.avg
gr__workids_granted.sum
 -arch:100:121:gr__workids_granted.sum
gr__workids_granted.min
 -arch:100:121:gr__workids_granted.min
gr__workids_granted.max
 -arch:100:121:gr__workids_granted.max
gr__workids_granted.avg
 -arch:100:121:gr__workids_granted.avg

In [58]:
!ncu --query-metrics | grep "dram"

dram__bytes                                                                 Counter         byte            # of bytes accessed in DRAM
dram__bytes_read                                                            Counter         byte            # of bytes read from DRAM
dram__bytes_write                                                           Counter         byte            # of bytes written to DRAM
dram__cycles_active                                                         Counter         cycle           # of cycles where DRAM was active
dram__cycles_active_read                                                    Counter         cycle           # of cycles where DRAM was active for reads
dram__cycles_active_write                                                   Counter         cycle           # of cycles where DRAM was active for writes
dram__cycles_elapsed                                                        Counter         cycle           # of elapsed DRAM memory clock cycles
dram__cycles_in_frame                                                       Counter         cycle           # of cycles in user-defined frame
dram__cycles_in_region                                                      Counter         cycle           # of cycles in user-defined region
dram__sectors                                                               Counter         sector          # of sectors accessed in DRAM
dram__sectors_read                                                          Counter         sector          # of sectors read from DRAM
dram__sectors_write                                                         Counter         sector          # of sectors written to DRAM
dram__throughput                                                            Throughput      %               DRAM throughput
fbpa__dram_cycles_elapsed                                                   Counter         cycle           # of cycles elapsed on DRAM
fbpa__dram_read_bytes                                                       Counter         byte            # of DRAM read bytes
fbpa__dram_read_sectors                                                     Counter         sector          # of DRAM read sectors
fbpa__dram_read_throughput                                                  Throughput      %               FBPA read throughput
fbpa__dram_sectors                                                          Counter         sector          # of DRAM sectors accessed
fbpa__dram_write_bytes                                                      Counter         byte            # of DRAM write bytes
fbpa__dram_write_sectors                                                    Counter         sector          # of DRAM write sectors
fbpa__dram_write_throughput                                                 Throughput      %               FBPA write throughput
gpu__dram_throughput                                                        Throughput      %               GPU DRAM throughput

Run ncu prifiling from device "0"

In [62]:
!ncu --devices 0 ./vector_add

==PROF== Connected to process 16594 (/content/vector_add)
==PROF== Profiling "vector_add" - 0: 0%....50%....100% - 10 passes
Result: 3.000000
==PROF== Disconnected from process 16594
[16594] vector_add@127.0.0.1
  vector_add(const float *, const float *, float *, int) (4096, 1, 1)x(256, 1, 1), Context 1, Stream 7, Device 0, CC 7.5
    Section: GPU Speed Of Light Throughput
    ----------------------- ----------- ------------
    Metric Name             Metric Unit Metric Value
    ----------------------- ----------- ------------
    DRAM Frequency                  Ghz         4.59
    SM Frequency                    Mhz       584.36
    Elapsed Cycles                cycle       29,422
    Memory Throughput                 %        90.08
    DRAM Throughput                   %        90.08
    Duration                         us        50.34
    L1/TEX Cache Throughput           %        31.70
    L2 Cache Throughput               %        28.70
    SM Active Cycles              cycle    25,433.75
    Compute (SM) Throughput           %        24.22
    ----------------------- ----------- ------------

    INF   This workload is utilizing greater than 80.0% of the available compute or memory performance of the device.
          To further improve performance, work will likely need to be shifted from the most utilized to another unit.
          Start by analyzing DRAM in the Memory Workload Analysis section.

    Section: Launch Statistics
    -------------------------------- --------------- ---------------
    Metric Name                          Metric Unit    Metric Value
    -------------------------------- --------------- ---------------
    Block Size                                                   256
    Function Cache Configuration                     CachePreferNone
    Grid Size                                                  4,096
    Registers Per Thread             register/thread              16
    Shared Memory Configuration Size           Kbyte           32.77
    Driver Shared Memory Per Block        byte/block               0
    Dynamic Shared Memory Per Block       byte/block               0
    Static Shared Memory Per Block        byte/block               0
    # SMs                                         SM              40
    Stack Size                                                 1,024
    Threads                                   thread       1,048,576
    # TPCs                                                        20
    Enabled TPC IDs                                              all
    Uses Green Context                                             0
    Waves Per SM                                               25.60
    -------------------------------- --------------- ---------------

    Section: Occupancy
    ------------------------------- ----------- ------------
    Metric Name                     Metric Unit Metric Value
    ------------------------------- ----------- ------------
    Block Limit SM                        block           16
    Block Limit Registers                 block           16
    Block Limit Shared Mem                block           16
    Block Limit Warps                     block            4
    Theoretical Active Warps per SM        warp           32
    Theoretical Occupancy                     %          100
    Achieved Occupancy                        %        88.62
    Achieved Active Warps Per SM           warp        28.36
    ------------------------------- ----------- ------------

    OPT   Est. Local Speedup: 11.38%
          The difference between calculated theoretical (100.0%) and measured achieved occupancy (88.6%) can be the
          result of warp scheduling overheads or workload imbalances during the kernel execution. Load imbalances can
          occur between warps within a block as well as across blocks of the same kernel. See the CUDA Best Practices
          Guide (https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#occupancy) for more details on
          optimizing occupancy.

    Section: GPU and Memory Workload Distribution
    -------------------------- ----------- ------------
    Metric Name                Metric Unit Metric Value
    -------------------------- ----------- ------------
    Average DRAM Active Cycles       cycle      208,001
    Total DRAM Elapsed Cycles        cycle    1,847,296
    Average L1 Active Cycles         cycle    25,433.75
    Total L1 Elapsed Cycles          cycle    1,082,480
    Average L2 Active Cycles         cycle    36,697.25
    Total L2 Elapsed Cycles          cycle    1,375,616
    Average SM Active Cycles         cycle    25,433.75
    Total SM Elapsed Cycles          cycle    1,082,480
    Average SMSP Active Cycles       cycle    25,408.92
    Total SMSP Elapsed Cycles        cycle    4,329,920
    -------------------------- ----------- ------------

In [64]:
!ncu --list-chips

ad102, ad103, ad104, ad106, ad107, ga100, ga102, ga103, ga104, ga106, ga107, ga10b, gb100, gb102, gb10b, gb110, gb202, gb203, gb205, gb206, gb207, gb20b, gh100, tu102, tu104, tu106, tu116, tu117

In [80]:
!ncu --section LaunchStats -o launch_stats -f ./vector_add

==PROF== Connected to process 19967 (/content/vector_add)
==PROF== Profiling "vector_add" - 0: 0%....50%....100% - 1 pass
Result: 3.000000
==PROF== Disconnected from process 19967
==PROF== Report: /content/launch_stats.ncu-rep

In [81]:
!ncu --import launch_stats.ncu-rep --csv --page details --log-file launch_stats.csv

| Argument      | What it does                                         | Simple explanation                                                                              |
|---------------|------------------------------------------------------|-------------------------------------------------------------------------------------------------|
| --import      | Loads an existing .ncu-rep profiling report.         | Read previously collected GPU profiling data instead of running the kernel again.               |
| --csv         | Formats profiling results as CSV (Comma-Separated Values). | Make the results readable by Excel, pandas, or other data tools.                         |
| --page details| Selects the detailed, section-based profiling report.| Show the collected performance metrics organized into sections such as Launch Statistics.       |
| --log-file    | Writes NCU's report output to the specified file.    | Save the results to launch_stats.csv instead of displaying them in the terminal.               |

In [86]:
!ncu --help | grep -A 15 -i "page"

  --page arg (=details)                 Select report page to output:
                                          details: sections and rules
                                          raw: all collected metrics
                                          source: source code
                                          session: session and device attributes
  --print-source arg                    Select source view:
                                          sass
                                          ptx
                                          cuda
                                          cuda,sass
                                         Metric correlation with source is available in sass, and cuda,sass source
                                        view.
                                         Metrics specified with --metrics and specified section file with --section are
                                        correlated.
                                         Consider restricting the number of selected metrics such that values fit into
                                        a single output row.
--
  --print-details arg (=header)         Select which part of a section should be shown in the details page output:
                                          header (default)
                                          (Show all metrics from header of the section)
                                          body
                                          (Show all metrics from body of the section)
                                          all
                                          (Show all metrics from the section)
  --print-metric-name arg (=label)      Select one of the option to show it in the Metric Name column:
                                          label (default)
                                          (Show metric label)
                                          name
                                          (Show metric name)
                                          label-name
                                          (Show both metric label and metric name)
  --print-units arg (=auto)             Set scaling of metric units. Allowed values:
                                          auto (default)

In [89]:
!ncu --help | grep -A 15 -i "log-file"

  --log-file arg                        Send all tool output to the specified file, or
                                          one of the standard channels. The file will be overwritten.
                                          If the file doesn't exist, a new one will be created.
                                          "stdout" as the whole file name indicates standard output
                                             channel (stdout). (default)
                                          "stderr" as the whole file name indicates standard error
                                             channel (stderr).
  -o [ --export ] arg                   Set the output file for writing the profile results. If not set, a temporary
                                        file will be used which is removed afterwards.
  -f [ --force-overwrite ]              Force overwriting all output, section or config files (any existing files will
                                        be overwritten).
  -i [ --import ] arg                   Set the input file for reading profile results.
  --open-in-ui                          Open report in UI instead of showing result on terminal.

Console Output Options:
  --csv                                 Use comma-separated values in the output. Implies --print-units base by

In [87]:
!ncu --import launch_stats.ncu-rep --csv --page raw --log-file launch_stats_raw.csv

In [82]:
import pandas as pd

df = pd.read_csv('launch_stats.csv')
df.head()

,ID,Process ID,Process Name,Host Name,Kernel Name,Context,Stream,Block Size,Grid Size,Device,CC,Section Name,Metric Name,Metric Unit,Metric Value,Rule Name,Rule Type,Rule Description,Estimated Speedup Type,Estimated Speedup
0,0,19967,vector_add,127.0.0.1,"vector_add(const float *, const float *, float...",1,7,"(256, 1, 1)","(4096, 1, 1)",0,7.5,Launch Statistics,Block Size,NaN,256,NaN,NaN,NaN,NaN,NaN
1,0,19967,vector_add,127.0.0.1,"vector_add(const float *, const float *, float...",1,7,"(256, 1, 1)","(4096, 1, 1)",0,7.5,Launch Statistics,Function Cache Configuration,NaN,CachePreferNone,NaN,NaN,NaN,NaN,NaN
2,0,19967,vector_add,127.0.0.1,"vector_add(const float *, const float *, float...",1,7,"(256, 1, 1)","(4096, 1, 1)",0,7.5,Launch Statistics,Grid Size,NaN,"4,096",NaN,NaN,NaN,NaN,NaN
3,0,19967,vector_add,127.0.0.1,"vector_add(const float *, const float *, float...",1,7,"(256, 1, 1)","(4096, 1, 1)",0,7.5,Launch Statistics,Registers Per Thread,register/thread,16,NaN,NaN,NaN,NaN,NaN
4,0,19967,vector_add,127.0.0.1,"vector_add(const float *, const float *, float...",1,7,"(256, 1, 1)","(4096, 1, 1)",0,7.5,Launch Statistics,Shared Memory Configuration Size,Kbyte,32.77,NaN,NaN,NaN,NaN,NaN

In [88]:
import pandas as pd

df = pd.read_csv('launch_stats_raw.csv')
df.head()

,ID,Process ID,Process Name,Host Name,Kernel Name,Context,Stream,Block Size,Grid Size,Device,...,profiler__perfworks_session_reuse,profiler__replayer_passes,profiler__replayer_passes_type_warmup,sm__maximum_warps_avg_per_active_cycle,sm__maximum_warps_per_active_cycle_pct,sm__warps_active.avg.pct_of_peak_sustained_active,sm__warps_active.max.pct_of_peak_sustained_active,sm__warps_active.min.pct_of_peak_sustained_active,sm__warps_active.sum.pct_of_peak_sustained_active,smsp__maximum_warps_avg_per_active_cycle
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,pass,pass,warp,%,%,%,%,%,warp
1,0.0,19967.0,vector_add,127.0.0.1,"vector_add(const float *, const float *, float...",1.0,7.0,"(256, 1, 1)","(4096, 1, 1)",0.0,...,0.0,1.000000,0,32.000000,100.000000,97.358386,99.410298,95.190282,97.358386,8.000000

You can't do this in remote (need to do this in SSH with X11 fowarding back to local)

In [90]:
!ncu --import launch_stats.ncu-rep --open-in-ui

qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland, xcb, wayland-egl, offscreen.

Application could not be initialized!
    This is likely due to missing Qt platform dependencies.
    For a list of dependencies, please refer to https://doc.qt.io/qt-6/linux-requirements.html
    To view missing libraries, set QT_DEBUG_PLUGINS=1 and re-run the application.

Warning: OpenGL Version check failed. Falling back to Mesa software rendering.
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland, xcb, wayland-egl, offscreen.

################# ERROR: CrashReporter #################
CrashReporter

Qt initialization failed

Failed to load Qt platform plugin: "xcb"
 - Library path: /opt/nvidia/nsight-compute/2025.3.1/host/linux-desktop-glibc_2_11_3-x64/Plugins/platforms/libqxcb.so
 - Error: libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory

Please check if libxkbcommon-x11.so.0 has been installed on your system
See https://doc.qt.io/qt-6/linux-requirements.html for more details.
Application is going to abort
sh: 1: xmessage: not found
Aborted (core dumped)
==ERROR== Failed to open the report in the UI.
==ERROR== An error occurred while trying to print the report.

In [94]:
!ncu --import launch_stats.ncu-rep --print-source sass --page source

------------------ ------------------------------------------------------
Kernel Name        vector_add(const float *, const float *, float *, int)
------------------ ------------------------------------------------------
Address            Source
0x780dc125a300          MOV R1, c[0x0][0x28]
0x780dc125a310          S2R R6, SR_CTAID.X
0x780dc125a320          S2R R3, SR_TID.X
0x780dc125a330          IMAD R6, R6, c[0x0][0x0], R3
0x780dc125a340          ISETP.GE.AND P0, PT, R6, c[0x0][0x178], PT
0x780dc125a350     @P0  EXIT
0x780dc125a360          MOV R7, 0x4
0x780dc125a370          IMAD.WIDE R4, R6, R7, c[0x0][0x168]
0x780dc125a380          IMAD.WIDE R2, R6, R7, c[0x0][0x160]
0x780dc125a390          LDG.E.SYS R4, [R4]
0x780dc125a3a0          LDG.E.SYS R3, [R2]
0x780dc125a3b0          IMAD.WIDE R6, R6, R7, c[0x0][0x170]
0x780dc125a3c0          FADD R9, R4, R3
0x780dc125a3d0          STG.E.SYS [R6], R9
0x780dc125a3e0          EXIT
0x780dc125a3f0          BRA 0x780dc125a3f0

In [95]:
!ncu --import launch_stats.ncu-rep --print-details header

[19967] vector_add@127.0.0.1
  vector_add(const float *, const float *, float *, int) (4096, 1, 1)x(256, 1, 1), Context 1, Stream 7, Device 0, CC 7.5
    Section: Launch Statistics
    -------------------------------- --------------- ---------------
    Metric Name                          Metric Unit    Metric Value
    -------------------------------- --------------- ---------------
    Block Size                                                   256
    Function Cache Configuration                     CachePreferNone
    Grid Size                                                  4,096
    Registers Per Thread             register/thread              16
    Shared Memory Configuration Size           Kbyte           32.77
    Driver Shared Memory Per Block        byte/block               0
    Dynamic Shared Memory Per Block       byte/block               0
    Static Shared Memory Per Block        byte/block               0
    # SMs                                         SM              40
    Stack Size                                                 1,024
    Threads                                   thread       1,048,576
    # TPCs                                                        20
    Enabled TPC IDs                                              all
    Uses Green Context                                             0
    Waves Per SM                                               25.60
    -------------------------------- --------------- ---------------

In [97]:
!ncu --import launch_stats.ncu-rep --print-metric-name label-name

[19967] vector_add@127.0.0.1
  vector_add(const float *, const float *, float *, int) (4096, 1, 1)x(256, 1, 1), Context 1, Stream 7, Device 0, CC 7.5
    Section: Launch Statistics
    ---------------------------------------------------------------------- --------------- ---------------
    Metric Name                                                                Metric Unit    Metric Value
    ---------------------------------------------------------------------- --------------- ---------------
    Block Size (launch__block_size)                                                                    256
    Function Cache Configuration (launch__func_cache_config)                               CachePreferNone
    Grid Size (launch__grid_size)                                                                    4,096
    Registers Per Thread (launch__registers_per_thread)                    register/thread              16
    Shared Memory Configuration Size (launch__shared_mem_config_size)                Kbyte           32.77
    Driver Shared Memory Per Block (launch__shared_mem_per_block_driver)        byte/block               0
    Dynamic Shared Memory Per Block (launch__shared_mem_per_block_dynamic)      byte/block               0
    Static Shared Memory Per Block (launch__shared_mem_per_block_static)        byte/block               0
    # SMs (launch__sm_count)                                                            SM              40
    Stack Size (launch__stack_size)                                                                  1,024
    Threads (launch__thread_count)                                                  thread       1,048,576
    # TPCs (launch__tpc_count)                                                                          20
    Enabled TPC IDs (launch__tpc_enabled)                                                              all
    Uses Green Context (launch__uses_green_context)                                                      0
    Waves Per SM (launch__waves_per_multiprocessor)                                                  25.60
    ---------------------------------------------------------------------- --------------- ---------------